-- ============================================================
-- 034: Materi (bilingual content) for the 12 sessions of the
--      "Data Analyst Fast Track · 2026" program (skeletons in 033).
--      Sourced from the curriculum's "Detail Learning Items".
--      Kept in a separate migration so content can be reviewed
--      independently of the structural seed.
-- ============================================================

-- ── X01 · Business Acumen dan Basic Statistics ──────────────
UPDATE public.sessions SET
 content_id = E'## Business Acumen dan Basic Statistics\n\n### 1. Apa itu Business Acumen\nKemampuan memahami bagaimana sebuah bisnis menghasilkan dan kehilangan uang, serta kenapa analyst wajib memilikinya. Contoh kasus retail/e-commerce: memahami margin, retensi, dan biaya akuisisi sebelum menyentuh data.\n\n### 2. Identifikasi Proses Bisnis & Metriks\n- Memetakan proses bisnis: **input → proses → output**\n- Memilih metriks yang relevan\n- **Leading indicator** (memprediksi, mis. jumlah lead) vs **lagging indicator** (hasil, mis. revenue)\n\n### 3. Problem Statement\n- Struktur dengan **5W1H** atau **issue tree** sederhana\n- Latihan mengubah pertanyaan samar (\"kenapa penjualan turun?\") jadi tajam dan terukur\n\n### 4. Basic Statistics\n- **Mean, median, modus** — ukuran pemusatan\n- **Range & standar deviasi** — ukuran sebaran\n- Kapan memakai masing-masing dan cara interpretasi sederhana\n\n> **Praktik:** Susun kertas kerja proses bisnis & metriks, lalu hitung ringkasan statistik sebuah dataset di Excel.',
 content_en = E'## Business Acumen and Basic Statistics\n\n### 1. What is Business Acumen\nThe ability to understand how a business makes and loses money, and why an analyst must have it. Retail/e-commerce example: understanding margin, retention, and acquisition cost before touching data.\n\n### 2. Identify Business Processes & Metrics\n- Map the business process: **input → process → output**\n- Choose relevant metrics\n- **Leading indicator** (predictive, e.g. number of leads) vs **lagging indicator** (outcome, e.g. revenue)\n\n### 3. Problem Statement\n- Structure it with **5W1H** or a simple **issue tree**\n- Practice turning a vague question (\"why did sales drop?\") into a sharp, measurable one\n\n### 4. Basic Statistics\n- **Mean, median, mode** — measures of central tendency\n- **Range & standard deviation** — measures of spread\n- When to use each and how to interpret them simply\n\n> **Practice:** Build a business-process & metrics worksheet, then compute a dataset''s summary statistics in Excel.'
WHERE session_number = 'X01';

-- ── X02 · Membersihkan dan Merapihkan Data ──────────────────
UPDATE public.sessions SET
 content_id = E'## Membersihkan dan Merapihkan Data\n\n### 1. Identifikasi Duplikat & Data Kosong\n- Mendeteksi baris duplikat; fitur **Remove Duplicates**\n- **Conditional Formatting** untuk menyorot sel blank/kosong\n- `=COUNTBLANK(range)` dan `=COUNTIF($A$2:$A$100, A2) > 1`\n\n### 2. Error Handling\nJenis error Excel umum dan penyebabnya:\n- `#N/A` (tidak ditemukan), `#REF!` (referensi hilang), `#VALUE!` (tipe salah), `#DIV/0!` (bagi nol)\n- Perbaiki dengan `=IFERROR(rumus, "pengganti")` dan `=IFNA(rumus, "tidak ditemukan")`\n\n### 3. TRIM, CONCAT, LEFT, RIGHT\n- `=TRIM(A2)` — hapus spasi berlebih\n- `=CONCAT(A2, " ", B2)` — gabung teks\n- `=LEFT(A2, 3)`, `=RIGHT(A2, 4)`, `=MID(...)` — ekstrak sebagian teks\n- Kombinasikan untuk menstandarkan format isian\n\n> **Praktik:** Rapikan dataset utama dengan prinsip data cleansing — hapus duplikat, tangani error, dan standarkan kolom teks.',
 content_en = E'## Cleaning and Shaping Data\n\n### 1. Identify Duplicates & Blank Data\n- Detect duplicate rows; the **Remove Duplicates** feature\n- **Conditional Formatting** to highlight blank/empty cells\n- `=COUNTBLANK(range)` and `=COUNTIF($A$2:$A$100, A2) > 1`\n\n### 2. Error Handling\nCommon Excel errors and their causes:\n- `#N/A` (not found), `#REF!` (lost reference), `#VALUE!` (wrong type), `#DIV/0!` (divide by zero)\n- Fix with `=IFERROR(formula, "fallback")` and `=IFNA(formula, "not found")`\n\n### 3. TRIM, CONCAT, LEFT, RIGHT\n- `=TRIM(A2)` — remove extra spaces\n- `=CONCAT(A2, " ", B2)` — join text\n- `=LEFT(A2, 3)`, `=RIGHT(A2, 4)`, `=MID(...)` — extract part of text\n- Combine them to standardize entry formats\n\n> **Practice:** Clean the main dataset with data-cleansing principles — remove duplicates, handle errors, and standardize text columns.'
WHERE session_number = 'X02';

-- ── X03 · Pivot Table untuk Dapatkan Insight ────────────────
UPDATE public.sessions SET
 content_id = E'## Pivot Table untuk Dapatkan Insight\n\n### 1. Analisa Kuantitatif — Pivot Table\nStruktur pivot table (**Rows, Columns, Values, Filters**) dan kapan pivot lebih tepat dibanding rumus manual.\n\n### 2. Latihan Pivot Table\n- Membuat pivot dari dataset mentah\n- Mengubah agregasi: **Sum, Count, Average**\n- Sorting & filtering di dalam pivot\n\n### 3. Pivot Table Advance\n- **Calculated Field**\n- **Grouping** data (per bulan/kuartal)\n- **Slicer** dan **Timeline** untuk interaktivitas\n\n### 4. Kasus Penjualan\nStudi kasus: mengidentifikasi produk terlaris, tren bulanan, dan kontribusi per kategori.\n\n> **Praktik:** Tarik insight dari dataset penjualan dengan pivot table dan fitur-fiturnya.',
 content_en = E'## Pivot Tables for Insight\n\n### 1. Quantitative Analysis — Pivot Table\nThe pivot table structure (**Rows, Columns, Values, Filters**) and when a pivot beats manual formulas.\n\n### 2. Pivot Table Practice\n- Build a pivot from a raw dataset\n- Change aggregation: **Sum, Count, Average**\n- Sorting & filtering inside the pivot\n\n### 3. Advanced Pivot Table\n- **Calculated Field**\n- **Grouping** data (by month/quarter)\n- **Slicer** and **Timeline** for interactivity\n\n### 4. Sales Case\nCase study: identify best-selling products, monthly trends, and contribution per category.\n\n> **Practice:** Draw insight from a sales dataset using a pivot table and its features.'
WHERE session_number = 'X03';

-- ── X04 · Data Collection dengan SQL ────────────────────────
UPDATE public.sessions SET
 content_id = E'## Data Collection dengan SQL\n\n### 1. Dasar SQL\n- `SELECT` kolom tertentu\n- `WHERE` untuk filter baris (`=`, `>`, `<`, `LIKE`, `IN`)\n- `ORDER BY` ASC/DESC\n- `GROUP BY` dengan agregat (`COUNT`, `SUM`, `AVG`)\n- `HAVING` untuk filter **setelah** agregasi (beda dengan `WHERE`)\n\n### 2. Mengambil Dataset dari Database\n- Menghubungkan ke database/sandbox\n- Memahami struktur tabel: kolom, tipe data, primary key\n\n### 3. Praktik Membuat Dataset\n- Menyusun query bertahap dari pertanyaan bisnis sederhana ke lebih kompleks\n- Menyimpan/export hasil query\n\n> **Praktik:** Buat sebuah dataset menggunakan SQL dasar.\n\n> 💡 Coba langsung di **Playground → SQL**.',
 content_en = E'## Data Collection with SQL\n\n### 1. SQL Basics\n- `SELECT` specific columns\n- `WHERE` to filter rows (`=`, `>`, `<`, `LIKE`, `IN`)\n- `ORDER BY` ASC/DESC\n- `GROUP BY` with aggregates (`COUNT`, `SUM`, `AVG`)\n- `HAVING` to filter **after** aggregation (unlike `WHERE`)\n\n### 2. Pulling a Dataset from a Database\n- Connect to a database/sandbox\n- Understand table structure: columns, data types, primary key\n\n### 3. Build-a-Dataset Practice\n- Compose queries step by step, from a simple business question to a more complex one\n- Save/export the query result\n\n> **Practice:** Build a dataset using basic SQL.\n\n> 💡 Try it live in **Playground → SQL**.'
WHERE session_number = 'X04';

-- ── X05 · Analisa Data dengan EDA ───────────────────────────
UPDATE public.sessions SET
 content_id = E'## Analisa Data dengan EDA\n\n### 1. Analisa Univariate & Bivariate\n- **Univariate:** distribusi, outlier, dan pemusatan satu variabel\n- **Bivariate:** hubungan antar dua variabel (korelasi, cross-tab)\n\n### 2. Cara Menarik Insight yang Baik\n- Membedakan **observasi** vs **insight** vs **rekomendasi**\n- Prinsip \"**so what?**\" di setiap temuan\n\n### 3. Study Case End-to-End\nAlur EDA lengkap pada satu dataset: eksplorasi awal → temuan → insight → rekomendasi bisnis.\n\n> **Praktik:** Hasilkan insight & rekomendasi dari sebuah case bisnis dengan prinsip EDA.',
 content_en = E'## Data Analysis with EDA\n\n### 1. Univariate & Bivariate Analysis\n- **Univariate:** distribution, outliers, and central tendency of one variable\n- **Bivariate:** the relationship between two variables (correlation, cross-tab)\n\n### 2. Drawing Good Insight\n- Distinguish **observation** vs **insight** vs **recommendation**\n- The \"**so what?**\" principle for every finding\n\n### 3. End-to-End Study Case\nA full EDA flow on one dataset: initial exploration → findings → insight → business recommendation.\n\n> **Practice:** Produce insight & recommendations from a business case using EDA principles.'
WHERE session_number = 'X05';

-- ── X06 · Visualisasi Data ──────────────────────────────────
UPDATE public.sessions SET
 content_id = E'## Visualisasi Data\n\n### 1. Prinsip, Warna & Layout Chart\n- Memilih jenis chart sesuai pertanyaan: perbandingan, tren, komposisi, distribusi\n- Prinsip penggunaan warna yang tidak menyesatkan\n- Layout dan hierarki visual\n\n### 2. Story with Data\n- Menyusun chart agar mendukung **satu pesan utama**, bukan sekadar menampilkan data\n- Menghindari chart membingungkan (dual axis, 3D, sumbu terpotong)\n\n### 3. Praktik Membuat Chart\nDari data mentah sampai chart final yang siap dipresentasikan.\n\n> **Praktik:** Buat chart efektif dari sebuah case bisnis.',
 content_en = E'## Data Visualization\n\n### 1. Principles, Color & Chart Layout\n- Choose a chart type by question: comparison, trend, composition, distribution\n- Principles of non-misleading color use\n- Layout and visual hierarchy\n\n### 2. Story with Data\n- Compose charts to support **one main message**, not just display data\n- Avoid confusing charts (dual axis, 3D, truncated axes)\n\n### 3. Chart-Building Practice\nFrom raw data to a final, presentation-ready chart.\n\n> **Practice:** Build an effective chart from a business case.'
WHERE session_number = 'X06';

-- ── X07 · Introduction to Power BI ──────────────────────────
UPDATE public.sessions SET
 content_id = E'## Introduction to Power BI\n\n### 1. Pengenalan Power BI & Chart\n- Instalasi & navigasi interface Power BI\n- Import data\n- Jenis visual dasar: bar, line, card, table\n\n### 2. Menyusun Dashboard\n- Menyusun layout dashboard yang jelas\n- Menghubungkan antar visual (**cross-filtering**)\n- Menambahkan filter/slicer\n\n### 3. Publish Dashboard\n- Langkah publish ke **Power BI Service**\n- Pengaturan sharing dan akses\n\n> **Praktik:** Buat dashboard dari sebuah case bisnis.',
 content_en = E'## Introduction to Power BI\n\n### 1. Power BI & Charts Intro\n- Install & navigate the Power BI interface\n- Import data\n- Basic visual types: bar, line, card, table\n\n### 2. Building a Dashboard\n- Lay out a clear dashboard\n- Link visuals together (**cross-filtering**)\n- Add filters/slicers\n\n### 3. Publish the Dashboard\n- Steps to publish to **Power BI Service**\n- Sharing and access settings\n\n> **Practice:** Build a dashboard from a business case.'
WHERE session_number = 'X07';

-- ── X08 · Python/Pandas 101 ─────────────────────────────────
UPDATE public.sessions SET
 content_id = E'## Python/Pandas 101\n\n### 1. Setup & Basic Python/Pandas\n- Instalasi environment; variabel & tipe data dasar\n- `import pandas`; membaca file (`read_csv`/`read_excel`)\n- Struktur **DataFrame** dan **Series**\n\n### 2. Matplotlib & Seaborn\n- Chart dasar dengan Matplotlib (line, bar)\n- Styling lebih baik dengan Seaborn\n- Menyimpan output chart\n\n### 3. Automation Laporan Excel (openpyxl)\n- Membaca & menulis file Excel via `openpyxl`\n- Format cell dan sheet otomatis\n- Menyusun laporan berulang secara otomatis\n\n> **Praktik:** Tarik insight dari sebuah dataset menggunakan Python.\n\n> 💡 Coba langsung di **Playground → Python**.',
 content_en = E'## Python/Pandas 101\n\n### 1. Setup & Basic Python/Pandas\n- Install the environment; variables & basic data types\n- `import pandas`; read files (`read_csv`/`read_excel`)\n- The **DataFrame** and **Series** structures\n\n### 2. Matplotlib & Seaborn\n- Basic charts with Matplotlib (line, bar)\n- Better styling with Seaborn\n- Save chart output\n\n### 3. Excel Report Automation (openpyxl)\n- Read & write Excel files via `openpyxl`\n- Automatic cell and sheet formatting\n- Automate a repeating report\n\n> **Practice:** Draw insight from a dataset using Python.\n\n> 💡 Try it live in **Playground → Python**.'
WHERE session_number = 'X08';

-- ── X09 · Analisis Data End-to-End dengan AI ────────────────
UPDATE public.sessions SET
 content_id = E'## Analisis Data End-to-End dengan AI\n\n### 1. Sistem Automation untuk Data Analysis\n- Konsep automation dalam alur kerja analisis data\n- Kapan dan kenapa AI membantu mempercepat proses\n\n### 2. Penggunaan Agentic AI\n- Memahami **agentic AI** — AI yang menjalankan langkah-langkah tanpa instruksi manual berulang\n- Batasan dan risiko: verifikasi hasil, privasi data\n\n### 3. Praktik Analisa Data dengan AI\n- Menyusun prompt untuk analisis **end-to-end**\n- Iterasi prompt untuk memperbaiki hasil\n- Validasi output AI terhadap data asli\n\n> **Praktik:** Susun prompt & lakukan iterasi dari sebuah case bisnis.',
 content_en = E'## End-to-End Data Analysis with AI\n\n### 1. Automation Systems for Data Analysis\n- The concept of automation in a data-analysis workflow\n- When and why AI speeds up the process\n\n### 2. Using Agentic AI\n- Understanding **agentic AI** — AI that runs steps without repeated manual instruction\n- Limits and risks: verifying results, data privacy\n\n### 3. AI Data-Analysis Practice\n- Write prompts for **end-to-end** analysis\n- Iterate prompts to improve results\n- Validate AI output against the source data\n\n> **Practice:** Write prompts & iterate on a business case.'
WHERE session_number = 'X09';

-- ── X10 · Analisa Data Lanjutan (UPSCALE) ───────────────────
UPDATE public.sessions SET
 content_id = E'## Analisa Data Lanjutan\n\n> 🚀 Sesi **Upscale** — tersedia untuk peserta jalur Extended.\n\n### 1. Segmentasi / Clustering\n- Konsep dasar segmentasi pelanggan\n- Kapan segmentasi dibutuhkan (retensi, targeting)\n\n### 2. Metode RFM\n- **Recency, Frequency, Monetary** — cara menghitung skor tiap dimensi\n- Menyusun kombinasi skor menjadi segmen pelanggan\n\n### 3. Praktik RFM & Segmentasi\n- Menerapkan RFM pada dataset nyata\n- Menginterpretasi hasil segmen menjadi rekomendasi bisnis\n\n> **Praktik:** Analisa berbasis RFM analysis.',
 content_en = E'## Advanced Data Analysis\n\n> 🚀 **Upscale** session — available to Extended-track learners.\n\n### 1. Segmentation / Clustering\n- Basics of customer segmentation\n- When segmentation is needed (retention, targeting)\n\n### 2. The RFM Method\n- **Recency, Frequency, Monetary** — how to score each dimension\n- Combine scores into customer segments\n\n### 3. RFM & Segmentation Practice\n- Apply RFM to a real dataset\n- Interpret the segments into business recommendations\n\n> **Practice:** Analysis based on RFM.'
WHERE session_number = 'X10';

-- ── X11 · Storytelling with Data (UPSCALE) ──────────────────
UPDATE public.sessions SET
 content_id = E'## Storytelling with Data\n\n> 🚀 Sesi **Upscale** — tersedia untuk peserta jalur Extended.\n\n### 1. Menyusun Deck Sesuai Kebutuhan Stakeholder\n- Memahami audiens/stakeholder\n- Menyesuaikan level detail dan bahasa sesuai kebutuhan mereka\n\n### 2. Narasi dari Data ke Rekomendasi\n- **Pyramid Principle** — kesimpulan dulu, baru pendukung\n- **Duarte narrative arc** untuk alur presentasi yang menarik\n\n### 3. Tips Storytelling Report\n- Satu pesan per slide\n- Visual mendukung, bukan mengulang teks\n- Urutan logis dari temuan ke rekomendasi\n\n> **Praktik:** Susun slide/PowerPoint dengan prinsip storytelling with data (Knaflic).',
 content_en = E'## Storytelling with Data\n\n> 🚀 **Upscale** session — available to Extended-track learners.\n\n### 1. Building a Deck for Stakeholder Needs\n- Understand the audience/stakeholder\n- Match the level of detail and language to their needs\n\n### 2. Narrative from Data to Recommendation\n- **Pyramid Principle** — conclusion first, then support\n- **Duarte narrative arc** for an engaging presentation flow\n\n### 3. Storytelling Report Tips\n- One message per slide\n- Visuals support, not repeat, the text\n- A logical order from finding to recommendation\n\n> **Practice:** Build a slide/PowerPoint deck using storytelling-with-data principles (Knaflic).'
WHERE session_number = 'X11';

-- ── X12 · Final Project dan Portofolio (UPSCALE) ────────────
UPDATE public.sessions SET
 content_id = E'## Final Project dan Portofolio\n\n> 🚀 Sesi **Upscale** — tersedia untuk peserta jalur Extended.\n\n### 1. Panduan Final Project End-to-End\n- Ruang lingkup dan ekspektasi final project\n- Kriteria penilaian (**rubrik**)\n- Timeline pengerjaan\n\n### 2. Menyusun Portofolio Profesional\n- Menonjolkan **proses berpikir**, bukan hanya hasil akhir\n- Mempresentasikan project di LinkedIn/platform lain untuk recruiter\n\n> **Praktik:** Susun portofolio profesional.',
 content_en = E'## Final Project and Portfolio\n\n> 🚀 **Upscale** session — available to Extended-track learners.\n\n### 1. End-to-End Final Project Guide\n- Scope and expectations of the final project\n- Grading criteria (**rubric**)\n- Work timeline\n\n### 2. Building a Professional Portfolio\n- Highlight your **thinking process**, not just the final result\n- Present the project on LinkedIn/other platforms for recruiters\n\n> **Practice:** Build a professional portfolio.'
WHERE session_number = 'X12';
