-- ============================================================
-- 050: Harder, scenario-based exercises for the Aug program.
--   The existing X-session sets were 4-pair definitional matches skewed
--   easy (2 easy / 1 medium / 1 hard). These add two APPLIED, judgement
--   based exercises per session — 5 pairs each, with plausible
--   distractors — so every session ends with a real difficulty ladder.
--
--   Auto-audited before generation: right-hand values are unique within
--   each exercise (the matching UI keys connections by that string, so a
--   duplicate makes an exercise impossible to complete) and test_cases
--   are emitted in pair order (the evaluator compares by index).
--
--   NOTE: applied to the live DB with shorter per-testcase feedback labels
--   (description_en/description_id). The pairs, expected_values, difficulty
--   and ordering are identical, so re-running this file reproduces the same
--   exercises; only the pass/fail label text differs cosmetically.
-- ============================================================

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Diagnose the Metric', 'Diagnosis Metrik', 'Each situation below hides a specific statistical trap. Match it to the correct diagnosis.', 'Setiap situasi di bawah menyembunyikan jebakan statistik tertentu. Cocokkan dengan diagnosis yang benar.',
  '{"pairs":[{"left":"Mean basket is 84.6 but the median is 49","right":"A few extreme outliers are inflating the mean"},{"left":"Revenue is flat while average fulfilment time climbs","right":"A leading indicator warning of a future revenue drop"},{"left":"Two stores share a mean of 50k; std dev is 5 vs 40","right":"Same average, very different consistency"},{"left":"Page views doubled but conversions did not move","right":"A vanity metric moving without business impact"},{"left":"Ice-cream and fan sales rise together every June","right":"Correlation produced by a shared third factor"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"A few extreme outliers are inflating the mean","description_en":"Mean basket is 84.6 but the median is 49 matched","description_id":"Mean basket is 84.6 but the median is 49 cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"A leading indicator warning of a future revenue drop","description_en":"Revenue is flat while average fulfilment time climbs matched","description_id":"Revenue is flat while average fulfilment time climbs cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Same average, very different consistency","description_en":"Two stores share a mean of 50k; std dev is 5 vs 40 matched","description_id":"Two stores share a mean of 50k; std dev is 5 vs 40 cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"A vanity metric moving without business impact","description_en":"Page views doubled but conversions did not move matched","description_id":"Page views doubled but conversions did not move cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Correlation produced by a shared third factor","description_en":"Ice-cream and fan sales rise together every June matched","description_id":"Ice-cream and fan sales rise together every June cocok","points":20}]'::jsonb, '["Compare mean against median to spot skew","Ask whether the metric predicts or merely reports"]'::jsonb, '["Bandingkan mean dengan median untuk melihat kemiringan","Tanyakan apakah metrik memprediksi atau hanya melaporkan"]'::jsonb, 'hard', 9
FROM public.sessions s WHERE s.session_number = 'X01'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Diagnose the Metric');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Sharpen the Question', 'Menajamkan Pertanyaan', 'Match each vague stakeholder request to the sharpened problem statement that makes it analysable.', 'Cocokkan setiap permintaan stakeholder yang samar dengan problem statement tajam yang membuatnya bisa dianalisis.',
  '{"pairs":[{"left":"Sales are bad","right":"Which categories drove the 12% MoM basket-size drop in Jakarta in March?"},{"left":"Are customers happy?","right":"Has 30-day repeat purchase changed since the April delivery-fee increase?"},{"left":"Should we open a new store?","right":"Do the 3 candidate districts have demand to break even within 12 months?"},{"left":"Marketing is not working","right":"Which channel had the lowest conversion per rupiah spent last quarter?"},{"left":"Fix the website","right":"Which checkout step lost the most users on mobile last month?"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"Which categories drove the 12% MoM basket-size drop in Jakarta in March?","description_en":"Sales are bad matched","description_id":"Sales are bad cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Has 30-day repeat purchase changed since the April delivery-fee increase?","description_en":"Are customers happy? matched","description_id":"Are customers happy? cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Do the 3 candidate districts have demand to break even within 12 months?","description_en":"Should we open a new store? matched","description_id":"Should we open a new store? cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"Which channel had the lowest conversion per rupiah spent last quarter?","description_en":"Marketing is not working matched","description_id":"Marketing is not working cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Which checkout step lost the most users on mobile last month?","description_en":"Fix the website matched","description_id":"Fix the website cocok","points":20}]'::jsonb, '["A sharp statement names what, where, when and the measure","Vague verbs like \"bad\" must become a number"]'::jsonb, '["Statement tajam menyebut apa, di mana, kapan, dan ukurannya","Kata samar seperti \"jelek\" harus jadi angka"]'::jsonb, 'hard', 10
FROM public.sessions s WHERE s.session_number = 'X01'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Sharpen the Question');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Pick the Right Fix', 'Pilih Perbaikan yang Tepat', 'Match each messy-data symptom to the formula that actually repairs it.', 'Cocokkan setiap gejala data berantakan dengan rumus yang benar-benar memperbaikinya.',
  '{"pairs":[{"left":"\"  budi  \" should read \"Budi\"","right":"=PROPER(TRIM(A2))"},{"left":"\"Rp 12.500\" refuses to SUM","right":"=VALUE(SUBSTITUTE(SUBSTITUTE(A2,\"Rp \",\"\"),\".\",\"\"))"},{"left":"A lookup shows #N/A for genuinely new items","right":"=IFNA(VLOOKUP(...),\"not found\")"},{"left":"TRIM ran but a stubborn space remains","right":"=SUBSTITUTE(A2,CHAR(160),\"\")"},{"left":"Extract 2024 out of \"INV-2024-0007\"","right":"=MID(A2,5,4)"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"=PROPER(TRIM(A2))","description_en":"\"  budi  \" should read \"Budi\" matched","description_id":"\"  budi  \" should read \"Budi\" cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"=VALUE(SUBSTITUTE(SUBSTITUTE(A2,\"Rp \",\"\"),\".\",\"\"))","description_en":"\"Rp 12.500\" refuses to SUM matched","description_id":"\"Rp 12.500\" refuses to SUM cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"=IFNA(VLOOKUP(...),\"not found\")","description_en":"A lookup shows #N/A for genuinely new items matched","description_id":"A lookup shows #N/A for genuinely new items cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"=SUBSTITUTE(A2,CHAR(160),\"\")","description_en":"TRIM ran but a stubborn space remains matched","description_id":"TRIM ran but a stubborn space remains cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"=MID(A2,5,4)","description_en":"Extract 2024 out of \"INV-2024-0007\" matched","description_id":"Extract 2024 out of \"INV-2024-0007\" cocok","points":20}]'::jsonb, '["A non-breaking space (char 160) survives TRIM","IFNA targets only #N/A, unlike IFERROR"]'::jsonb, '["Non-breaking space (char 160) lolos dari TRIM","IFNA khusus #N/A, beda dari IFERROR"]'::jsonb, 'hard', 9
FROM public.sessions s WHERE s.session_number = 'X02'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Pick the Right Fix');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Cleaning Judgement Calls', 'Keputusan saat Membersihkan', 'Cleaning is judgement, not reflex. Match each situation to the right decision.', 'Membersihkan itu penilaian, bukan refleks. Cocokkan setiap situasi dengan keputusan yang tepat.',
  '{"pairs":[{"left":"Two identical rows, same order_id","right":"A true duplicate — safe to remove"},{"left":"Two rows, same customer, different order_id","right":"Two real orders — keep both"},{"left":"A blank phone number","right":"Missing contact info — flag, do not delete the row"},{"left":"A blank order total on a shipped order","right":"A data error worth escalating before analysis"},{"left":"=IFERROR(revenue/orders, 0) on a real bug","right":"Hides the fault and reports a misleading zero"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"A true duplicate — safe to remove","description_en":"Two identical rows, same order_id matched","description_id":"Two identical rows, same order_id cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Two real orders — keep both","description_en":"Two rows, same customer, different order_id matched","description_id":"Two rows, same customer, different order_id cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Missing contact info — flag, do not delete the row","description_en":"A blank phone number matched","description_id":"A blank phone number cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"A data error worth escalating before analysis","description_en":"A blank order total on a shipped order matched","description_id":"A blank order total on a shipped order cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Hides the fault and reports a misleading zero","description_en":"=IFERROR(revenue/orders, 0) on a real bug matched","description_id":"=IFERROR(revenue/orders, 0) on a real bug cocok","points":20}]'::jsonb, '["A repeated key is not the same as a repeated customer","IFERROR can silently disguise a genuine problem"]'::jsonb, '["Kunci berulang tidak sama dengan pelanggan berulang","IFERROR bisa diam-diam menyamarkan masalah nyata"]'::jsonb, 'hard', 10
FROM public.sessions s WHERE s.session_number = 'X02'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Cleaning Judgement Calls');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Pivot Table Troubleshooting', 'Menelusuri Masalah Pivot Table', 'Match each pivot symptom to its actual cause.', 'Cocokkan setiap gejala pivot dengan penyebab sebenarnya.',
  '{"pairs":[{"left":"New rows added but the pivot ignores them","right":"The source is a fixed range, not a Table"},{"left":"Values show Count when you expect Sum","right":"Blanks or text are mixed into the numeric column"},{"left":"Dates will not group into months","right":"The dates are stored as text, not real dates"},{"left":"Numbers look stale after the source changed","right":"The pivot has not been refreshed"},{"left":"Percentages do not add up to the total shown","right":"Show Values As is set to the wrong base"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"The source is a fixed range, not a Table","description_en":"New rows added but the pivot ignores them matched","description_id":"New rows added but the pivot ignores them cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Blanks or text are mixed into the numeric column","description_en":"Values show Count when you expect Sum matched","description_id":"Values show Count when you expect Sum cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"The dates are stored as text, not real dates","description_en":"Dates will not group into months matched","description_id":"Dates will not group into months cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"The pivot has not been refreshed","description_en":"Numbers look stale after the source changed matched","description_id":"Numbers look stale after the source changed cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Show Values As is set to the wrong base","description_en":"Percentages do not add up to the total shown matched","description_id":"Percentages do not add up to the total shown cocok","points":20}]'::jsonb, '["Pivots never auto-refresh","A single text cell changes how a column aggregates"]'::jsonb, '["Pivot tidak pernah refresh otomatis","Satu sel teks mengubah cara kolom diagregasi"]'::jsonb, 'hard', 9
FROM public.sessions s WHERE s.session_number = 'X03'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Pivot Table Troubleshooting');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Configure the Pivot', 'Mengonfigurasi Pivot', 'Match each business question to the pivot configuration that answers it.', 'Cocokkan setiap pertanyaan bisnis dengan konfigurasi pivot yang menjawabnya.',
  '{"pairs":[{"left":"Revenue by category for each month","right":"Category in Rows, Month in Columns, Sum of revenue"},{"left":"Each category share of the grand total","right":"Sum of revenue, Show Values As % of Grand Total"},{"left":"Cumulative revenue across the year","right":"Sum of revenue, Show Values As Running Total"},{"left":"Let a viewer switch region without editing","right":"Add a Region Slicer"},{"left":"Profit where only revenue and cost exist","right":"Add a Calculated Field: revenue - cost"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"Category in Rows, Month in Columns, Sum of revenue","description_en":"Revenue by category for each month matched","description_id":"Revenue by category for each month cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Sum of revenue, Show Values As % of Grand Total","description_en":"Each category share of the grand total matched","description_id":"Each category share of the grand total cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Sum of revenue, Show Values As Running Total","description_en":"Cumulative revenue across the year matched","description_id":"Cumulative revenue across the year cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"Add a Region Slicer","description_en":"Let a viewer switch region without editing matched","description_id":"Let a viewer switch region without editing cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Add a Calculated Field: revenue - cost","description_en":"Profit where only revenue and cost exist matched","description_id":"Profit where only revenue and cost exist cocok","points":20}]'::jsonb, '["Two dimensions means Rows plus Columns","Show Values As reframes the same number"]'::jsonb, '["Dua dimensi berarti Rows plus Columns","Show Values As membingkai ulang angka yang sama"]'::jsonb, 'hard', 10
FROM public.sessions s WHERE s.session_number = 'X03'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Configure the Pivot');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Read the Signal', 'Membaca Sinyal', 'Match each EDA finding to the correct interpretation.', 'Cocokkan setiap temuan EDA dengan interpretasi yang benar.',
  '{"pairs":[{"left":"A long right tail in basket size","right":"Skewed data — report the median, not the mean"},{"left":"Correlation of +0.9 between discount and returns","right":"They move together strongly, but cause is unproven"},{"left":"Overall churn is flat, but every segment rose","right":"A mix shift is hiding the trend (Simpson paradox)"},{"left":"A box plot with many points beyond the whiskers","right":"Outliers worth investigating before modelling"},{"left":"Two variables with correlation near 0","right":"No linear relationship — a curve may still exist"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"Skewed data — report the median, not the mean","description_en":"A long right tail in basket size matched","description_id":"A long right tail in basket size cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"They move together strongly, but cause is unproven","description_en":"Correlation of +0.9 between discount and returns matched","description_id":"Correlation of +0.9 between discount and returns cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"A mix shift is hiding the trend (Simpson paradox)","description_en":"Overall churn is flat, but every segment rose matched","description_id":"Overall churn is flat, but every segment rose cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"Outliers worth investigating before modelling","description_en":"A box plot with many points beyond the whiskers matched","description_id":"A box plot with many points beyond the whiskers cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"No linear relationship — a curve may still exist","description_en":"Two variables with correlation near 0 matched","description_id":"Two variables with correlation near 0 cocok","points":20}]'::jsonb, '["Correlation measures linear association only","An overall average can contradict every subgroup"]'::jsonb, '["Korelasi hanya mengukur hubungan linear","Rata-rata keseluruhan bisa bertentangan dengan tiap subgrup"]'::jsonb, 'hard', 9
FROM public.sessions s WHERE s.session_number = 'X05'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Read the Signal');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'From Finding to Recommendation', 'Dari Temuan ke Rekomendasi', 'Match each analytical step to the statement that belongs at that level.', 'Cocokkan setiap tahap analitis dengan pernyataan yang sesuai levelnya.',
  '{"pairs":[{"left":"Observation","right":"Jakarta accounts for 40% of revenue"},{"left":"Insight","right":"Jakarta over-indexes because premium members cluster there"},{"left":"Recommendation","right":"Pilot a premium Electronics bundle in Jakarta next quarter"},{"left":"Hypothesis to test next","right":"Does premium density also predict basket size elsewhere?"},{"left":"Not worth reporting","right":"The table contains 12,480 rows"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"Jakarta accounts for 40% of revenue","description_en":"Observation matched","description_id":"Observation cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Jakarta over-indexes because premium members cluster there","description_en":"Insight matched","description_id":"Insight cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Pilot a premium Electronics bundle in Jakarta next quarter","description_en":"Recommendation matched","description_id":"Recommendation cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"Does premium density also predict basket size elsewhere?","description_en":"Hypothesis to test next matched","description_id":"Hypothesis to test next cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"The table contains 12,480 rows","description_en":"Not worth reporting matched","description_id":"Not worth reporting cocok","points":20}]'::jsonb, '["An insight explains why, an observation only states what","Row counts alone do not drive decisions"]'::jsonb, '["Insight menjelaskan kenapa, observasi hanya menyatakan apa","Jumlah baris saja tidak mendorong keputusan"]'::jsonb, 'hard', 10
FROM public.sessions s WHERE s.session_number = 'X05'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'From Finding to Recommendation');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Fix the Misleading Chart', 'Memperbaiki Chart yang Menyesatkan', 'Match each charting mistake to the fix that makes it honest.', 'Cocokkan setiap kesalahan chart dengan perbaikan yang membuatnya jujur.',
  '{"pairs":[{"left":"Bar chart y-axis starts at 95","right":"Start the bar axis at zero"},{"left":"Two series on separate axes implying a link","right":"Split into two charts or index both to a common base"},{"left":"A pie with nine slices","right":"Use a sorted bar chart instead"},{"left":"Every category in a different bright colour","right":"Grey everything, colour only the point being made"},{"left":"Title reads \"Revenue by Month\"","right":"Retitle it with the takeaway the chart proves"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"Start the bar axis at zero","description_en":"Bar chart y-axis starts at 95 matched","description_id":"Bar chart y-axis starts at 95 cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Split into two charts or index both to a common base","description_en":"Two series on separate axes implying a link matched","description_id":"Two series on separate axes implying a link cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Use a sorted bar chart instead","description_en":"A pie with nine slices matched","description_id":"A pie with nine slices cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"Grey everything, colour only the point being made","description_en":"Every category in a different bright colour matched","description_id":"Every category in a different bright colour cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Retitle it with the takeaway the chart proves","description_en":"Title reads \"Revenue by Month\" matched","description_id":"Title reads \"Revenue by Month\" cocok","points":20}]'::jsonb, '["Truncated bar axes exaggerate small differences","The title is prime real estate for your message"]'::jsonb, '["Sumbu bar terpotong melebih-lebihkan beda kecil","Judul adalah tempat terbaik untuk pesan Anda"]'::jsonb, 'hard', 9
FROM public.sessions s WHERE s.session_number = 'X06'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Fix the Misleading Chart');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Chart Choice Under Constraint', 'Memilih Chart dengan Batasan', 'Match each specific request to the most appropriate chart.', 'Cocokkan setiap permintaan spesifik dengan chart yang paling tepat.',
  '{"pairs":[{"left":"Rank 12 branches by revenue","right":"Sorted horizontal bar chart"},{"left":"Show 36 months of revenue and a seasonal pattern","right":"Line chart"},{"left":"Show how delivery times are distributed","right":"Histogram"},{"left":"Compare category mix across 4 regions","right":"100% stacked bar chart"},{"left":"Show whether discount predicts return rate","right":"Scatter plot with a trend line"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"Sorted horizontal bar chart","description_en":"Rank 12 branches by revenue matched","description_id":"Rank 12 branches by revenue cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Line chart","description_en":"Show 36 months of revenue and a seasonal pattern matched","description_id":"Show 36 months of revenue and a seasonal pattern cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Histogram","description_en":"Show how delivery times are distributed matched","description_id":"Show how delivery times are distributed cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"100% stacked bar chart","description_en":"Compare category mix across 4 regions matched","description_id":"Compare category mix across 4 regions cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Scatter plot with a trend line","description_en":"Show whether discount predicts return rate matched","description_id":"Show whether discount predicts return rate cocok","points":20}]'::jsonb, '["Long category labels favour horizontal bars","100% stacked compares composition, not size"]'::jsonb, '["Label kategori panjang cocok untuk bar horizontal","100% stacked membandingkan komposisi, bukan ukuran"]'::jsonb, 'hard', 10
FROM public.sessions s WHERE s.session_number = 'X06'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Chart Choice Under Constraint');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Troubleshoot the Dashboard', 'Menelusuri Masalah Dashboard', 'Match each Power BI symptom to its cause.', 'Cocokkan setiap gejala Power BI dengan penyebabnya.',
  '{"pairs":[{"left":"A region slicer filters one visual but not the others","right":"A relationship between the tables is missing"},{"left":"Published report shows last month data","right":"Scheduled refresh is not configured"},{"left":"Totals double after adding a table","right":"A one-to-many relationship is duplicating rows"},{"left":"A measure ignores the slicer selection","right":"The calculation was written as a static column"},{"left":"Numbers are right but the page is unreadable","right":"Too many visuals — one page should answer one question"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"A relationship between the tables is missing","description_en":"A region slicer filters one visual but not the others matched","description_id":"A region slicer filters one visual but not the others cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Scheduled refresh is not configured","description_en":"Published report shows last month data matched","description_id":"Published report shows last month data cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"A one-to-many relationship is duplicating rows","description_en":"Totals double after adding a table matched","description_id":"Totals double after adding a table cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"The calculation was written as a static column","description_en":"A measure ignores the slicer selection matched","description_id":"A measure ignores the slicer selection cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Too many visuals — one page should answer one question","description_en":"Numbers are right but the page is unreadable matched","description_id":"Numbers are right but the page is unreadable cocok","points":20}]'::jsonb, '["Relationships drive cross-filtering","A measure recalculates with filters; a column does not"]'::jsonb, '["Relasi menggerakkan cross-filtering","Measure dihitung ulang oleh filter; kolom tidak"]'::jsonb, 'hard', 9
FROM public.sessions s WHERE s.session_number = 'X07'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Troubleshoot the Dashboard');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Model or Measure?', 'Model atau Measure?', 'Match each requirement to the correct Power BI mechanism.', 'Cocokkan setiap kebutuhan dengan mekanisme Power BI yang benar.',
  '{"pairs":[{"left":"Total revenue that responds to every slicer","right":"A DAX measure"},{"left":"Clean and retype a messy import","right":"Power Query"},{"left":"Let orders be filtered by customer region","right":"A relationship on customer_id"},{"left":"Average order value from two measures","right":"DIVIDE of revenue by order count"},{"left":"Share the report with the finance team","right":"Publish to a Workspace and grant access"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"A DAX measure","description_en":"Total revenue that responds to every slicer matched","description_id":"Total revenue that responds to every slicer cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Power Query","description_en":"Clean and retype a messy import matched","description_id":"Clean and retype a messy import cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"A relationship on customer_id","description_en":"Let orders be filtered by customer region matched","description_id":"Let orders be filtered by customer region cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"DIVIDE of revenue by order count","description_en":"Average order value from two measures matched","description_id":"Average order value from two measures cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Publish to a Workspace and grant access","description_en":"Share the report with the finance team matched","description_id":"Share the report with the finance team cocok","points":20}]'::jsonb, '["Measures live at query time, transforms at load time","DIVIDE handles divide-by-zero safely"]'::jsonb, '["Measure saat query, transformasi saat load","DIVIDE menangani pembagian nol dengan aman"]'::jsonb, 'hard', 10
FROM public.sessions s WHERE s.session_number = 'X07'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Model or Measure?');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Debug the pandas Error', 'Men-debug Error pandas', 'Match each pandas symptom to its real cause or fix.', 'Cocokkan setiap gejala pandas dengan penyebab atau perbaikannya.',
  '{"pairs":[{"left":"SettingWithCopyWarning appears","right":"You edited a slice — work on .copy() instead"},{"left":"df[\"revenue\"].sum() returns a joined string","right":"The column is text; convert with pd.to_numeric"},{"left":"df[df.a>1 & df.b<2] raises an error","right":"Wrap each condition in parentheses"},{"left":"to_excel adds a stray leading column","right":"Pass index=False"},{"left":"describe() omits a numeric-looking column","right":"Its dtype is object, not a number"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"You edited a slice — work on .copy() instead","description_en":"SettingWithCopyWarning appears matched","description_id":"SettingWithCopyWarning appears cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"The column is text; convert with pd.to_numeric","description_en":"df[\"revenue\"].sum() returns a joined string matched","description_id":"df[\"revenue\"].sum() returns a joined string cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Wrap each condition in parentheses","description_en":"df[df.a>1 & df.b<2] raises an error matched","description_id":"df[df.a>1 & df.b<2] raises an error cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"Pass index=False","description_en":"to_excel adds a stray leading column matched","description_id":"to_excel adds a stray leading column cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Its dtype is object, not a number","description_en":"describe() omits a numeric-looking column matched","description_id":"describe() omits a numeric-looking column cocok","points":20}]'::jsonb, '["Check dtypes with df.info() before aggregating","& binds tighter than the comparisons around it"]'::jsonb, '["Cek dtype dengan df.info() sebelum mengagregasi","& mengikat lebih kuat dari perbandingan di sekitarnya"]'::jsonb, 'hard', 9
FROM public.sessions s WHERE s.session_number = 'X08'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Debug the pandas Error');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Choose the pandas Operation', 'Memilih Operasi pandas', 'Match each task to the pandas expression that performs it.', 'Cocokkan setiap tugas dengan ekspresi pandas yang melakukannya.',
  '{"pairs":[{"left":"Revenue per category","right":"df.groupby(\"category\")[\"revenue\"].sum()"},{"left":"Keep only orders above one million","right":"df[df[\"revenue\"] > 1000000]"},{"left":"Inspect column types and null counts","right":"df.info()"},{"left":"Attach product names to an orders table","right":"df.merge(products, on=\"product_id\")"},{"left":"Write the summary out for stakeholders","right":"df.to_excel(\"report.xlsx\", index=False)"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"df.groupby(\"category\")[\"revenue\"].sum()","description_en":"Revenue per category matched","description_id":"Revenue per category cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"df[df[\"revenue\"] > 1000000]","description_en":"Keep only orders above one million matched","description_id":"Keep only orders above one million cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"df.info()","description_en":"Inspect column types and null counts matched","description_id":"Inspect column types and null counts cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"df.merge(products, on=\"product_id\")","description_en":"Attach product names to an orders table matched","description_id":"Attach product names to an orders table cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"df.to_excel(\"report.xlsx\", index=False)","description_en":"Write the summary out for stakeholders matched","description_id":"Write the summary out for stakeholders cocok","points":20}]'::jsonb, '["merge is the pandas equivalent of a SQL join","groupby splits, applies, then combines"]'::jsonb, '["merge adalah padanan JOIN SQL di pandas","groupby memecah, menerapkan, lalu menggabungkan"]'::jsonb, 'hard', 10
FROM public.sessions s WHERE s.session_number = 'X08'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Choose the pandas Operation');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Spot the AI Failure Mode', 'Mengenali Mode Kegagalan AI', 'Match each AI output problem to what actually went wrong.', 'Cocokkan setiap masalah output AI dengan apa yang sebenarnya terjadi.',
  '{"pairs":[{"left":"A clean table citing a column that does not exist","right":"Hallucinated schema — verify against the source"},{"left":"Average order value silently includes cancelled orders","right":"An unstated assumption in the filter"},{"left":"A confident answer with no calculation shown","right":"Unverifiable — ask it to show its working"},{"left":"A generic summary that fits any dataset","right":"The prompt lacked context and constraints"},{"left":"Customer emails pasted into a public tool","right":"A privacy breach — anonymise or use an approved tool"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"Hallucinated schema — verify against the source","description_en":"A clean table citing a column that does not exist matched","description_id":"A clean table citing a column that does not exist cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"An unstated assumption in the filter","description_en":"Average order value silently includes cancelled orders matched","description_id":"Average order value silently includes cancelled orders cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Unverifiable — ask it to show its working","description_en":"A confident answer with no calculation shown matched","description_id":"A confident answer with no calculation shown cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"The prompt lacked context and constraints","description_en":"A generic summary that fits any dataset matched","description_id":"A generic summary that fits any dataset cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"A privacy breach — anonymise or use an approved tool","description_en":"Customer emails pasted into a public tool matched","description_id":"Customer emails pasted into a public tool cocok","points":20}]'::jsonb, '["Always recompute one number against the real data","Vague prompts return filler"]'::jsonb, '["Selalu hitung ulang satu angka ke data asli","Prompt samar menghasilkan jawaban generik"]'::jsonb, 'hard', 9
FROM public.sessions s WHERE s.session_number = 'X09'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Spot the AI Failure Mode');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Repair the Prompt', 'Memperbaiki Prompt', 'Match each weak prompt to the element it is missing.', 'Cocokkan setiap prompt lemah dengan elemen yang hilang.',
  '{"pairs":[{"left":"\"Analyse this data\"","right":"Missing a specific task"},{"left":"\"Find the top categories\"","right":"Missing the metric and time window"},{"left":"\"Give me insights, be thorough\"","right":"Missing an output format"},{"left":"\"Use any columns you think fit\"","right":"Missing constraints on the data"},{"left":"\"You are a data expert. Analyse.\"","right":"Missing the actual dataset context"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"Missing a specific task","description_en":"\"Analyse this data\" matched","description_id":"\"Analyse this data\" cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Missing the metric and time window","description_en":"\"Find the top categories\" matched","description_id":"\"Find the top categories\" cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Missing an output format","description_en":"\"Give me insights, be thorough\" matched","description_id":"\"Give me insights, be thorough\" cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"Missing constraints on the data","description_en":"\"Use any columns you think fit\" matched","description_id":"\"Use any columns you think fit\" cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Missing the actual dataset context","description_en":"\"You are a data expert. Analyse.\" matched","description_id":"\"You are a data expert. Analyse.\" cocok","points":20}]'::jsonb, '["A strong prompt has context, task, format and constraints","Persona alone is not context"]'::jsonb, '["Prompt kuat punya konteks, tugas, format, dan batasan","Persona saja bukan konteks"]'::jsonb, 'hard', 10
FROM public.sessions s WHERE s.session_number = 'X09'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Repair the Prompt');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Assign the RFM Segment', 'Menentukan Segmen RFM', 'Match each customer profile to its RFM segment.', 'Cocokkan setiap profil pelanggan dengan segmen RFM-nya.',
  '{"pairs":[{"left":"Bought last week, 20 orders, very high spend","right":"Champion"},{"left":"Was a top buyer, nothing for 9 months","right":"At Risk"},{"left":"First order arrived three days ago","right":"New"},{"left":"Buys small amounts often, every month","right":"Loyal but low value"},{"left":"One tiny order, two years ago","right":"Lost"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"Champion","description_en":"Bought last week, 20 orders, very high spend matched","description_id":"Bought last week, 20 orders, very high spend cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"At Risk","description_en":"Was a top buyer, nothing for 9 months matched","description_id":"Was a top buyer, nothing for 9 months cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"New","description_en":"First order arrived three days ago matched","description_id":"First order arrived three days ago cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"Loyal but low value","description_en":"Buys small amounts often, every month matched","description_id":"Buys small amounts often, every month cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Lost","description_en":"One tiny order, two years ago matched","description_id":"One tiny order, two years ago cocok","points":20}]'::jsonb, '["Recency is scored inverted — fewer days is better","High F with low R is the classic At Risk shape"]'::jsonb, '["Recency dinilai terbalik — makin sedikit hari makin baik","F tinggi dengan R rendah adalah bentuk klasik At Risk"]'::jsonb, 'hard', 9
FROM public.sessions s WHERE s.session_number = 'X10'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Assign the RFM Segment');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Segment to Budget Decision', 'Segmen ke Keputusan Anggaran', 'Match each segment to the action that spends money best.', 'Cocokkan setiap segmen dengan aksi yang paling tepat guna anggarannya.',
  '{"pairs":[{"left":"Champions","right":"Reward and ask for referrals, do not discount"},{"left":"At Risk","right":"Targeted win-back before they churn"},{"left":"New","right":"Nurture toward a second purchase"},{"left":"Loyal but low value","right":"Encourage a larger basket, not more visits"},{"left":"Lost","right":"One cheap reactivation attempt, then stop spending"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"Reward and ask for referrals, do not discount","description_en":"Champions matched","description_id":"Champions cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Targeted win-back before they churn","description_en":"At Risk matched","description_id":"At Risk cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Nurture toward a second purchase","description_en":"New matched","description_id":"New cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"Encourage a larger basket, not more visits","description_en":"Loyal but low value matched","description_id":"Loyal but low value cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"One cheap reactivation attempt, then stop spending","description_en":"Lost matched","description_id":"Lost cocok","points":20}]'::jsonb, '["Discounting people who already buy destroys margin","Not every segment deserves the same budget"]'::jsonb, '["Memberi diskon ke yang sudah pasti beli merusak margin","Tidak semua segmen layak anggaran yang sama"]'::jsonb, 'hard', 10
FROM public.sessions s WHERE s.session_number = 'X10'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Segment to Budget Decision');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Diagnose the Deck', 'Diagnosis Deck', 'Match each presentation failure to the fix.', 'Cocokkan setiap kegagalan presentasi dengan perbaikannya.',
  '{"pairs":[{"left":"The recommendation appears on slide 22","right":"Lead with the conclusion (Pyramid Principle)"},{"left":"Executives ask \"so what should we do?\"","right":"End on an explicit call to action"},{"left":"The presenter reads the slide aloud","right":"Cut to one message plus a supporting visual"},{"left":"Finance disengages halfway through","right":"Reframe the impact in money — ROI and payback"},{"left":"Every slide title is a topic label","right":"Retitle each slide with its takeaway"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"Lead with the conclusion (Pyramid Principle)","description_en":"The recommendation appears on slide 22 matched","description_id":"The recommendation appears on slide 22 cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"End on an explicit call to action","description_en":"Executives ask \"so what should we do?\" matched","description_id":"Executives ask \"so what should we do?\" cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Cut to one message plus a supporting visual","description_en":"The presenter reads the slide aloud matched","description_id":"The presenter reads the slide aloud cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"Reframe the impact in money — ROI and payback","description_en":"Finance disengages halfway through matched","description_id":"Finance disengages halfway through cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Retitle each slide with its takeaway","description_en":"Every slide title is a topic label matched","description_id":"Every slide title is a topic label cocok","points":20}]'::jsonb, '["Busy audiences need the answer first","Titles should assert, not label"]'::jsonb, '["Audiens sibuk butuh jawaban lebih dulu","Judul harus menegaskan, bukan melabeli"]'::jsonb, 'hard', 9
FROM public.sessions s WHERE s.session_number = 'X11'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Diagnose the Deck');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Tailor to the Audience', 'Menyesuaikan dengan Audiens', 'Match each audience to the move that actually lands with them.', 'Cocokkan setiap audiens dengan langkah yang benar-benar mengena.',
  '{"pairs":[{"left":"CEO with five minutes","right":"One slide: decision, impact, the ask"},{"left":"Analyst reviewing your method","right":"Show assumptions, joins and caveats"},{"left":"Finance approving budget","right":"Lead with ROI and payback period"},{"left":"Ops team executing the change","right":"Concrete steps with owners and dates"},{"left":"A mixed audience","right":"Headline for all, detail in an appendix"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"One slide: decision, impact, the ask","description_en":"CEO with five minutes matched","description_id":"CEO with five minutes cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Show assumptions, joins and caveats","description_en":"Analyst reviewing your method matched","description_id":"Analyst reviewing your method cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Lead with ROI and payback period","description_en":"Finance approving budget matched","description_id":"Finance approving budget cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"Concrete steps with owners and dates","description_en":"Ops team executing the change matched","description_id":"Ops team executing the change cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Headline for all, detail in an appendix","description_en":"A mixed audience matched","description_id":"A mixed audience cocok","points":20}]'::jsonb, '["Detail level is an audience decision, not a taste one","An appendix keeps depth without derailing the room"]'::jsonb, '["Level detail adalah keputusan audiens, bukan selera","Appendix menyimpan kedalaman tanpa mengganggu ruangan"]'::jsonb, 'hard', 10
FROM public.sessions s WHERE s.session_number = 'X11'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Tailor to the Audience');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Grade Against the Rubric', 'Menilai dengan Rubrik', 'Match each project weakness to the rubric criterion it fails.', 'Cocokkan setiap kelemahan proyek dengan kriteria rubrik yang gagal dipenuhi.',
  '{"pairs":[{"left":"The question is \"explore the sales data\"","right":"Problem framing"},{"left":"Duplicate rows were never removed","right":"Data handling"},{"left":"Only counts and averages, no segmentation","right":"Analysis depth"},{"left":"Charts shown with no interpretation","right":"Insight quality"},{"left":"A 40-slide deck with no structure","right":"Communication"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"Problem framing","description_en":"The question is \"explore the sales data\" matched","description_id":"The question is \"explore the sales data\" cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Data handling","description_en":"Duplicate rows were never removed matched","description_id":"Duplicate rows were never removed cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Analysis depth","description_en":"Only counts and averages, no segmentation matched","description_id":"Only counts and averages, no segmentation cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"Insight quality","description_en":"Charts shown with no interpretation matched","description_id":"Charts shown with no interpretation cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Communication","description_en":"A 40-slide deck with no structure matched","description_id":"A 40-slide deck with no structure cocok","points":20}]'::jsonb, '["Framing is judged before any analysis","Charts without a so-what fail on insight, not visuals"]'::jsonb, '["Framing dinilai sebelum analisis apa pun","Chart tanpa so-what gagal di insight, bukan visual"]'::jsonb, 'hard', 9
FROM public.sessions s WHERE s.session_number = 'X12'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Grade Against the Rubric');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id, starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, order_num)
SELECT s.id, 'matching', 'Portfolio Decisions', 'Keputusan Portofolio', 'Match each portfolio choice to its effect on a recruiter.', 'Cocokkan setiap pilihan portofolio dengan dampaknya pada recruiter.',
  '{"pairs":[{"left":"README opens with the business finding","right":"Immediately shows impact"},{"left":"README opens with the tech stack","right":"Reads as tool-listing, not outcomes"},{"left":"Three complete end-to-end projects","right":"Demonstrates you can finish work"},{"left":"Ten unfinished notebooks","right":"Signals nothing was ever completed"},{"left":"Documented assumptions and dead ends","right":"Proves the thinking is genuinely yours"}]}', '', '[{"id":"tc1","validation_type":"matching","expected_value":"Immediately shows impact","description_en":"README opens with the business finding matched","description_id":"README opens with the business finding cocok","points":20},{"id":"tc2","validation_type":"matching","expected_value":"Reads as tool-listing, not outcomes","description_en":"README opens with the tech stack matched","description_id":"README opens with the tech stack cocok","points":20},{"id":"tc3","validation_type":"matching","expected_value":"Demonstrates you can finish work","description_en":"Three complete end-to-end projects matched","description_id":"Three complete end-to-end projects cocok","points":20},{"id":"tc4","validation_type":"matching","expected_value":"Signals nothing was ever completed","description_en":"Ten unfinished notebooks matched","description_id":"Ten unfinished notebooks cocok","points":20},{"id":"tc5","validation_type":"matching","expected_value":"Proves the thinking is genuinely yours","description_en":"Documented assumptions and dead ends matched","description_id":"Documented assumptions and dead ends cocok","points":20}]'::jsonb, '["Recruiters hire outcomes, not syntax","Showing your reasoning is what cannot be copied"]'::jsonb, '["Recruiter merekrut hasil, bukan sintaks","Menunjukkan penalaran adalah yang tak bisa disalin"]'::jsonb, 'hard', 10
FROM public.sessions s WHERE s.session_number = 'X12'
  AND NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.session_id = s.id AND e.title_en = 'Portfolio Decisions');


