-- ============================================================
-- 055: X04 SQL exercises rebuilt on the Seduh Coffee dataset.
--
--   The X01-X12 program builds one portfolio project on the Seduh data, so the
--   SQL session now practises on that data instead of the synthetic ecommerce
--   schema. Every exercise is one of the brief's own business questions, and
--   the learner's playground totals match the workbook on their disk.
--
--   dataset_name moves to 'seduh', which is what routes the browser to the
--   right database. The 04/05/06/F08 sessions keep 'ecommerce' and are
--   untouched.
--
--   Generated by scripts/gen-x04-exercises.py — every expected value below was
--   produced by executing the solution against the real dataset. Do not edit by
--   hand; re-run the script instead.
-- ============================================================

DELETE FROM public.exercises
WHERE session_id = (SELECT id FROM public.sessions WHERE session_number = 'X04');

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Roasted Beans, Most Expensive First', 'Roasted Beans, Termahal Dulu', 'Seduh sells six categories. List every product in the **Roasted Beans** category, most expensive first. Return exactly: `product_name`, `base_price`.', 'Seduh menjual enam kategori. Tampilkan semua produk kategori **Roasted Beans**, termahal dulu. Kembalikan tepat: `product_name`, `base_price`.',
  '-- Roasted Beans products, most expensive first
-- Return: product_name, base_price
', 'SELECT product_name, base_price FROM products WHERE category = ''Roasted Beans'' ORDER BY base_price DESC;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"product_name": "House Blend 1kg", "base_price": 349000}, {"product_name": "House Blend 500g", "base_price": 195000}, {"product_name": "Cold Brew Blend 500g", "base_price": 178000}, {"product_name": "Single Origin Sampler 4x100g", "base_price": 165000}, {"product_name": "Manuk Gading Natural 200g", "base_price": 145000}, {"product_name": "Decaf Blend 200g", "base_price": 135000}, {"product_name": "Arabika Toraja Sapan 200g", "base_price": 125000}, {"product_name": "Arabika Flores Bajawa 200g", "base_price": 122000}, {"product_name": "Arabika Kintamani Bali 200g", "base_price": 118000}, {"product_name": "Arabika Gayo Aceh 200g", "base_price": 115000}, {"product_name": "Arabika Java Preanger 200g", "base_price": 110000}, {"product_name": "Espresso Blend 250g", "base_price": 99000}, {"product_name": "House Blend 200g", "base_price": 89000}, {"product_name": "Robusta Lampung 250g", "base_price": 78000}], "description_en": "Returns the correct 14 row(s) with the right values", "description_id": "Mengembalikan 14 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["product_name", "base_price"], "description_en": "Returns the required columns: product_name, base_price", "description_id": "Mengembalikan kolom yang diminta: product_name, base_price", "points": 30}]'::jsonb,
  '["Filter with WHERE category = ...", "ORDER BY ... DESC puts the largest first"]'::jsonb,
  '["Filter dengan WHERE category = ...", "ORDER BY ... DESC menaruh yang terbesar dulu"]'::jsonb,
  'easy', 'seduh', 1
FROM public.sessions s WHERE s.session_number = 'X04';

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Which Channels Does Seduh Sell On?', 'Seduh Berjualan di Channel Apa Saja?', 'Count the **completed** orders per sales channel. Remember: only `order_status = ''Completed''` counts. Return exactly: `channel`, `orders`, busiest first.', 'Hitung jumlah order **Completed** per channel penjualan. Ingat: hanya `order_status = ''Completed''` yang dihitung. Kembalikan tepat: `channel`, `orders`, terbanyak dulu.',
  '-- Completed orders per channel
-- Return: channel, orders
', 'SELECT channel, COUNT(*) AS orders FROM orders WHERE order_status = ''Completed'' GROUP BY channel ORDER BY orders DESC;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"channel": "Tokopedia", "orders": 6831}, {"channel": "Shopee", "orders": 6640}, {"channel": "Webstore", "orders": 5016}, {"channel": "TikTok Shop", "orders": 3986}], "description_en": "Returns the correct 4 row(s) with the right values", "description_id": "Mengembalikan 4 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["channel", "orders"], "description_en": "Returns the required columns: channel, orders", "description_id": "Mengembalikan kolom yang diminta: channel, orders", "points": 30}]'::jsonb,
  '["WHERE filters rows before grouping", "COUNT(*) counts rows in each group"]'::jsonb,
  '["WHERE memfilter baris sebelum pengelompokan", "COUNT(*) menghitung baris di tiap grup"]'::jsonb,
  'easy', 'seduh', 2
FROM public.sessions s WHERE s.session_number = 'X04';

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Q2 — Which Channel Is Most Valuable After Discount?', 'Q2 — Channel Mana yang Paling Bernilai Setelah Diskon?', 'Gross revenue flatters a discount-heavy channel. Compute revenue **after** discount: `quantity * unit_price * (1 - discount_pct)`, completed orders only. Return exactly: `channel`, `revenue` (rounded, no decimals), highest first.', 'Revenue kotor membuat channel yang banyak diskon terlihat bagus. Hitung revenue **setelah** diskon: `quantity * unit_price * (1 - discount_pct)`, hanya order Completed. Kembalikan tepat: `channel`, `revenue` (dibulatkan, tanpa desimal), tertinggi dulu.',
  '-- Q2: revenue after discount, per channel
-- Return: channel, revenue
', 'SELECT channel, ROUND(SUM(quantity * unit_price * (1 - discount_pct))) AS revenue FROM orders WHERE order_status = ''Completed'' GROUP BY channel ORDER BY revenue DESC;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"channel": "Tokopedia", "revenue": 1952745250.0}, {"channel": "Shopee", "revenue": 1895463500.0}, {"channel": "Webstore", "revenue": 1465035900.0}, {"channel": "TikTok Shop", "revenue": 1152241300.0}], "description_en": "Returns the correct 4 row(s) with the right values", "description_id": "Mengembalikan 4 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["channel", "revenue"], "description_en": "Returns the required columns: channel, revenue", "description_id": "Mengembalikan kolom yang diminta: channel, revenue", "points": 30}]'::jsonb,
  '["Discount is a fraction — multiply by (1 - discount_pct)", "Wrap the SUM in ROUND() so the result has no decimals"]'::jsonb,
  '["Diskon berupa pecahan — kalikan dengan (1 - discount_pct)", "Bungkus SUM dengan ROUND() agar hasilnya tanpa desimal"]'::jsonb,
  'medium', 'seduh', 3
FROM public.sessions s WHERE s.session_number = 'X04';

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Q1 — Profit by Category, Not Revenue', 'Q1 — Profit per Kategori, Bukan Revenue', 'The category that sells most is not always the one that earns most. `unit_cost` lives in `products`, so you need a JOIN. Profit per line is `quantity * (unit_price * (1 - discount_pct) - unit_cost)`, completed orders only. Return exactly: `category`, `profit` (rounded), highest first.', 'Kategori yang paling laku belum tentu yang paling untung. `unit_cost` ada di `products`, jadi kamu butuh JOIN. Profit per baris = `quantity * (unit_price * (1 - discount_pct) - unit_cost)`, hanya order Completed. Kembalikan tepat: `category`, `profit` (dibulatkan), tertinggi dulu.',
  '-- Q1: profit per category (needs products.unit_cost)
-- Return: category, profit
', 'SELECT p.category, ROUND(SUM(o.quantity * (o.unit_price * (1 - o.discount_pct) - p.unit_cost))) AS profit FROM orders o JOIN products p ON p.product_id = o.product_id WHERE o.order_status = ''Completed'' GROUP BY p.category ORDER BY profit DESC;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"category": "Roasted Beans", "profit": 1730492250.0}, {"category": "Ready to Drink", "profit": 417608050.0}, {"category": "Accessories", "profit": 302351900.0}, {"category": "Brewing Equipment", "profit": 251506200.0}, {"category": "Subscription", "profit": 217073050.0}, {"category": "Gift Set", "profit": 211455000.0}], "description_en": "Returns the correct 6 row(s) with the right values", "description_id": "Mengembalikan 6 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["category", "profit"], "description_en": "Returns the required columns: category, profit", "description_id": "Mengembalikan kolom yang diminta: category, profit", "points": 30}]'::jsonb,
  '["JOIN products ON p.product_id = o.product_id", "Subtract unit_cost per unit, then multiply by quantity"]'::jsonb,
  '["JOIN products ON p.product_id = o.product_id", "Kurangi unit_cost per unit, lalu kalikan dengan quantity"]'::jsonb,
  'medium', 'seduh', 4
FROM public.sessions s WHERE s.session_number = 'X04';

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Q3 — Monthly Revenue in 2025', 'Q3 — Revenue Bulanan di 2025', 'Build the 2025 trend. `order_date` is text in `YYYY-MM-DD` form, so `substr(order_date, 1, 7)` gives you the month. Completed orders only. Return exactly: `month`, `revenue` (rounded), in date order.', 'Bangun tren 2025. `order_date` berupa teks `YYYY-MM-DD`, jadi `substr(order_date, 1, 7)` memberi bulannya. Hanya order Completed. Kembalikan tepat: `month`, `revenue` (dibulatkan), urut tanggal.',
  '-- Q3: monthly revenue for 2025 only
-- Return: month, revenue
', 'SELECT substr(order_date, 1, 7) AS month, ROUND(SUM(quantity * unit_price * (1 - discount_pct))) AS revenue FROM orders WHERE order_status = ''Completed'' AND order_date >= ''2025-01-01'' AND order_date < ''2026-01-01'' GROUP BY month ORDER BY month;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"month": "2025-01", "revenue": 249916300.0}, {"month": "2025-02", "revenue": 260051750.0}, {"month": "2025-03", "revenue": 337374100.0}, {"month": "2025-04", "revenue": 342545800.0}, {"month": "2025-05", "revenue": 328439250.0}, {"month": "2025-06", "revenue": 375867400.0}, {"month": "2025-07", "revenue": 351188550.0}, {"month": "2025-08", "revenue": 400672950.0}, {"month": "2025-09", "revenue": 429498100.0}, {"month": "2025-10", "revenue": 429585000.0}, {"month": "2025-11", "revenue": 449284200.0}, {"month": "2025-12", "revenue": 468854200.0}], "description_en": "Returns the correct 12 row(s) with the right values", "description_id": "Mengembalikan 12 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["month", "revenue"], "description_en": "Returns the required columns: month, revenue", "description_id": "Mengembalikan kolom yang diminta: month, revenue", "points": 30}]'::jsonb,
  '["substr(order_date, 1, 7) turns 2025-03-14 into 2025-03", "Filter the year in WHERE, then GROUP BY the month expression"]'::jsonb,
  '["substr(order_date, 1, 7) mengubah 2025-03-14 menjadi 2025-03", "Filter tahunnya di WHERE, lalu GROUP BY ekspresi bulan tersebut"]'::jsonb,
  'medium', 'seduh', 5
FROM public.sessions s WHERE s.session_number = 'X04';

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Cities Worth Their Own Campaign', 'Kota yang Layak Dapat Kampanye Sendiri', 'Which cities have more than 900 completed orders? Filtering on a COUNT needs `HAVING`, not `WHERE`. Return exactly: `city`, `orders`, busiest first.', 'Kota mana yang punya lebih dari 900 order Completed? Memfilter hasil COUNT butuh `HAVING`, bukan `WHERE`. Kembalikan tepat: `city`, `orders`, terbanyak dulu.',
  '-- Cities with more than 900 completed orders
-- Return: city, orders
', 'SELECT city, COUNT(*) AS orders FROM orders WHERE order_status = ''Completed'' GROUP BY city HAVING COUNT(*) > 900 ORDER BY orders DESC;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"city": "Jakarta", "orders": 5467}, {"city": "Bandung", "orders": 2578}, {"city": "Surabaya", "orders": 2103}, {"city": "Semarang", "orders": 1310}, {"city": "Yogyakarta", "orders": 1242}, {"city": "Bekasi", "orders": 1129}, {"city": "Denpasar", "orders": 1022}, {"city": "Medan", "orders": 1017}, {"city": "Bogor", "orders": 990}, {"city": "Tangerang", "orders": 908}], "description_en": "Returns the correct 10 row(s) with the right values", "description_id": "Mengembalikan 10 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["city", "orders"], "description_en": "Returns the required columns: city, orders", "description_id": "Mengembalikan kolom yang diminta: city, orders", "points": 30}]'::jsonb,
  '["WHERE runs before grouping, HAVING runs after", "You still need the completed-orders filter in WHERE"]'::jsonb,
  '["WHERE berjalan sebelum pengelompokan, HAVING sesudahnya", "Filter order Completed tetap diperlukan di WHERE"]'::jsonb,
  'hard', 'seduh', 6
FROM public.sessions s WHERE s.session_number = 'X04';

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Q6 — Which Acquisition Channel Brings the Best Customers?', 'Q6 — Channel Akuisisi Mana yang Membawa Customer Terbaik?', 'Join `orders` to `customers` and group by `acquisition_channel`. Return exactly: `acquisition_channel`, `customers` (distinct buyers), `revenue` (rounded), highest revenue first. Completed orders only.', 'Join `orders` ke `customers` lalu kelompokkan per `acquisition_channel`. Kembalikan tepat: `acquisition_channel`, `customers` (pembeli unik), `revenue` (dibulatkan), revenue tertinggi dulu. Hanya order Completed.',
  '-- Q6: value of each acquisition channel
-- Return: acquisition_channel, customers, revenue
', 'SELECT c.acquisition_channel, COUNT(DISTINCT o.customer_id) AS customers, ROUND(SUM(o.quantity * o.unit_price * (1 - o.discount_pct))) AS revenue FROM orders o JOIN customers c ON c.customer_id = o.customer_id WHERE o.order_status = ''Completed'' GROUP BY c.acquisition_channel ORDER BY revenue DESC;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"acquisition_channel": "Instagram Ads", "customers": 1262, "revenue": 1989875250.0}, {"acquisition_channel": "TikTok Ads", "customers": 1011, "revenue": 1561529000.0}, {"acquisition_channel": "Google Search", "customers": 534, "revenue": 854672250.0}, {"acquisition_channel": "Organic Social", "customers": 514, "revenue": 745397250.0}, {"acquisition_channel": "Marketplace", "customers": 403, "revenue": 664570050.0}, {"acquisition_channel": "Referral", "customers": 428, "revenue": 649442150.0}], "description_en": "Returns the correct 6 row(s) with the right values", "description_id": "Mengembalikan 6 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["acquisition_channel", "customers", "revenue"], "description_en": "Returns the required columns: acquisition_channel, customers, revenue", "description_id": "Mengembalikan kolom yang diminta: acquisition_channel, customers, revenue", "points": 30}]'::jsonb,
  '["COUNT(DISTINCT ...) so a repeat buyer is not counted twice", "Spend lives in marketing_spend, but its channel names differ — that is the next step"]'::jsonb,
  '["COUNT(DISTINCT ...) agar repeat buyer tidak terhitung dua kali", "Spend ada di marketing_spend, tapi nama channel-nya berbeda — itu langkah berikutnya"]'::jsonb,
  'hard', 'seduh', 7
FROM public.sessions s WHERE s.session_number = 'X04';

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Q7 — Does Discounting Actually Pay?', 'Q7 — Apakah Diskon Benar-benar Menguntungkan?', 'Group completed order lines by `discount_pct` and compare average quantity against margin. Margin percent is `profit / revenue * 100`. Return exactly: `discount_pct`, `avg_quantity` (rounded to 2 decimals), `margin_pct` (rounded to 1 decimal), by discount ascending. Read the answer off your own result.', 'Kelompokkan baris order Completed per `discount_pct` dan bandingkan rata-rata quantity dengan margin. Margin persen = `profit / revenue * 100`. Kembalikan tepat: `discount_pct`, `avg_quantity` (2 desimal), `margin_pct` (1 desimal), urut diskon menaik. Baca jawabannya dari hasilmu sendiri.',
  '-- Q7: discount depth vs volume vs margin
-- Return: discount_pct, avg_quantity, margin_pct
', 'SELECT o.discount_pct, ROUND(AVG(o.quantity), 2) AS avg_quantity, ROUND(SUM(o.quantity * (o.unit_price * (1 - o.discount_pct) - p.unit_cost)) * 100.0 / SUM(o.quantity * o.unit_price * (1 - o.discount_pct)), 1) AS margin_pct FROM orders o JOIN products p ON p.product_id = o.product_id WHERE o.order_status = ''Completed'' GROUP BY o.discount_pct ORDER BY o.discount_pct;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"discount_pct": 0.0, "avg_quantity": 2.46, "margin_pct": 50.8}, {"discount_pct": 0.05, "avg_quantity": 2.43, "margin_pct": 48.9}, {"discount_pct": 0.1, "avg_quantity": 2.38, "margin_pct": 45.2}, {"discount_pct": 0.15, "avg_quantity": 2.41, "margin_pct": 42.4}, {"discount_pct": 0.2, "avg_quantity": 2.3, "margin_pct": 38.3}, {"discount_pct": 0.25, "avg_quantity": 2.41, "margin_pct": 34.6}], "description_en": "Returns the correct 6 row(s) with the right values", "description_id": "Mengembalikan 6 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["discount_pct", "avg_quantity", "margin_pct"], "description_en": "Returns the required columns: discount_pct, avg_quantity, margin_pct", "description_id": "Mengembalikan kolom yang diminta: discount_pct, avg_quantity, margin_pct", "points": 30}]'::jsonb,
  '["Compute profit and revenue in the same query, then divide", "Multiply by 100.0 — integer division would flatten the result to 0"]'::jsonb,
  '["Hitung profit dan revenue dalam satu query, lalu bagi", "Kalikan dengan 100.0 — pembagian integer akan membuat hasilnya 0"]'::jsonb,
  'hard', 'seduh', 8
FROM public.sessions s WHERE s.session_number = 'X04';
