-- ============================================================
-- 063: X04 SQL exercises re-keyed to the September 2026 Seduh dataset.
--
--   Supersedes 055 (and the X04 description rewrites in 059, which are folded
--   back into the generator). The playground now serves the RAW tables rather
--   than the cleaned ones — more rows, duplicate order_id values, mixed
--   channel spellings — so every expected value from 055 was stale.
--
--   The X01-X12 program builds one portfolio project on the Seduh data, so the
--   SQL session now practises on that data instead of the synthetic ecommerce
--   schema. Every exercise is one of the brief's own business questions, and
--   the learner's playground totals match the workbook on their disk.
--
--   dataset_name moves to 'seduh', which is what routes the browser to the
--   right database. The 04/05/06/F08 sessions keep 'ecommerce' and are
--   untouched.
--
--   Generated by scripts/gen-x04-exercises.py — every expected value below was
--   produced by executing the solution against the real dataset. Do not edit by
--   hand; re-run the script instead.
--
--   UPDATE in place, matched on order_num, rather than DELETE + INSERT like 055
--   did: exercise_submissions.exercise_id cascades on delete, so re-inserting
--   would take every learner's submitted attempt with it. The row's identity is
--   what has to survive; only its content changes.
--
--   An INSERT is still emitted, guarded by NOT EXISTS, so a database that never
--   ran 055 ends up with the same eight exercises.
-- ============================================================

-- #1 — Roasted Beans, Most Expensive First
UPDATE public.exercises e
SET type = 'sql',
    title_en = 'Roasted Beans, Most Expensive First',
    title_id = 'Roasted Beans, Termahal Dulu',
    description_en = 'Seduh sells six categories. List every product in the **Roasted Beans** category, most expensive first. Return exactly: `product_name`, `base_price`. This is the raw data, so `category` is not spelled consistently yet — match the exact value and note which rows that leaves out.',
    description_id = 'Seduh menjual enam kategori. Tampilkan semua produk kategori **Roasted Beans**, termahal dulu. Kembalikan tepat: `product_name`, `base_price`. Ini data mentah, jadi penulisan `category` belum seragam — cocokkan nilai persisnya dan perhatikan baris mana yang jadi tidak ikut.',
    starter_code = '-- Roasted Beans products, most expensive first
-- Return: product_name, base_price
',
    solution_code = 'SELECT product_name, base_price FROM products WHERE category = ''Roasted Beans'' ORDER BY base_price DESC;',
    test_cases = '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"product_name": "House Blend 1kg", "base_price": 349000}, {"product_name": "House Blend 500g", "base_price": 195000}, {"product_name": "Cold Brew Blend 500g", "base_price": 178000}, {"product_name": "Single Origin Sampler 4x100g", "base_price": 165000}, {"product_name": "Manuk Gading Natural 200g", "base_price": 145000}, {"product_name": "Decaf Blend 200g", "base_price": 135000}, {"product_name": "Arabika Toraja Sapan 200g", "base_price": 125000}, {"product_name": "Arabika Flores Bajawa 200g", "base_price": 122000}, {"product_name": "Arabika Kintamani Bali 200g", "base_price": 118000}, {"product_name": "Arabika Java Preanger 200g", "base_price": 110000}, {"product_name": "Espresso Blend 250g", "base_price": 99000}, {"product_name": "House Blend 200g", "base_price": 89000}, {"product_name": "Robusta Lampung 250g", "base_price": 78000}], "description_en": "Returns the correct 13 row(s) with the right values", "description_id": "Mengembalikan 13 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["product_name", "base_price"], "description_en": "Returns the required columns: product_name, base_price", "description_id": "Mengembalikan kolom yang diminta: product_name, base_price", "points": 30}]'::jsonb,
    hints_en = '["Filter with WHERE category = ...", "ORDER BY ... DESC puts the largest first"]'::jsonb,
    hints_id = '["Filter dengan WHERE category = ...", "ORDER BY ... DESC menaruh yang terbesar dulu"]'::jsonb,
    difficulty = 'easy',
    dataset_name = 'seduh'
FROM public.sessions s
WHERE e.session_id = s.id AND s.session_number = 'X04' AND e.order_num = 1;

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Roasted Beans, Most Expensive First', 'Roasted Beans, Termahal Dulu', 'Seduh sells six categories. List every product in the **Roasted Beans** category, most expensive first. Return exactly: `product_name`, `base_price`. This is the raw data, so `category` is not spelled consistently yet — match the exact value and note which rows that leaves out.', 'Seduh menjual enam kategori. Tampilkan semua produk kategori **Roasted Beans**, termahal dulu. Kembalikan tepat: `product_name`, `base_price`. Ini data mentah, jadi penulisan `category` belum seragam — cocokkan nilai persisnya dan perhatikan baris mana yang jadi tidak ikut.',
  '-- Roasted Beans products, most expensive first
-- Return: product_name, base_price
', 'SELECT product_name, base_price FROM products WHERE category = ''Roasted Beans'' ORDER BY base_price DESC;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"product_name": "House Blend 1kg", "base_price": 349000}, {"product_name": "House Blend 500g", "base_price": 195000}, {"product_name": "Cold Brew Blend 500g", "base_price": 178000}, {"product_name": "Single Origin Sampler 4x100g", "base_price": 165000}, {"product_name": "Manuk Gading Natural 200g", "base_price": 145000}, {"product_name": "Decaf Blend 200g", "base_price": 135000}, {"product_name": "Arabika Toraja Sapan 200g", "base_price": 125000}, {"product_name": "Arabika Flores Bajawa 200g", "base_price": 122000}, {"product_name": "Arabika Kintamani Bali 200g", "base_price": 118000}, {"product_name": "Arabika Java Preanger 200g", "base_price": 110000}, {"product_name": "Espresso Blend 250g", "base_price": 99000}, {"product_name": "House Blend 200g", "base_price": 89000}, {"product_name": "Robusta Lampung 250g", "base_price": 78000}], "description_en": "Returns the correct 13 row(s) with the right values", "description_id": "Mengembalikan 13 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["product_name", "base_price"], "description_en": "Returns the required columns: product_name, base_price", "description_id": "Mengembalikan kolom yang diminta: product_name, base_price", "points": 30}]'::jsonb,
  '["Filter with WHERE category = ...", "ORDER BY ... DESC puts the largest first"]'::jsonb,
  '["Filter dengan WHERE category = ...", "ORDER BY ... DESC menaruh yang terbesar dulu"]'::jsonb,
  'easy', 'seduh', 1
FROM public.sessions s
WHERE s.session_number = 'X04'
  AND NOT EXISTS (
    SELECT 1 FROM public.exercises x
    WHERE x.session_id = s.id AND x.order_num = 1);

-- #2 — Which Channels Does Seduh Sell On?
UPDATE public.exercises e
SET type = 'sql',
    title_en = 'Which Channels Does Seduh Sell On?',
    title_id = 'Seduh Berjualan di Channel Apa Saja?',
    description_en = 'Count the **completed** orders per sales channel. Remember: only `order_status = ''Completed''` counts. Return exactly: `channel`, `orders`, busiest first. The data is raw, so you will get far more than four channels — that mess is the finding.',
    description_id = 'Hitung jumlah order **Completed** per channel penjualan. Ingat: hanya `order_status = ''Completed''` yang dihitung. Kembalikan tepat: `channel`, `orders`, terbanyak dulu. Datanya mentah, jadi channel-nya akan jauh lebih dari empat — keberantakan itulah temuannya.',
    starter_code = '-- Completed orders per channel
-- Return: channel, orders
',
    solution_code = 'SELECT channel, COUNT(*) AS orders FROM orders WHERE order_status = ''Completed'' GROUP BY channel ORDER BY orders DESC;',
    test_cases = '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"channel": "Tokopedia", "orders": 6857}, {"channel": "Shopee", "orders": 6520}, {"channel": "Webstore", "orders": 5073}, {"channel": "TikTok Shop", "orders": 4838}, {"channel": "Webstore ", "orders": 52}, {"channel": "tokopedia", "orders": 50}, {"channel": " Webstore", "orders": 50}, {"channel": "WEBSTORE", "orders": 45}, {"channel": "Shoppee", "orders": 44}, {"channel": " Shopee", "orders": 44}, {"channel": "Tiktok shop ", "orders": 39}, {"channel": "TIKTOK SHOP", "orders": 37}, {"channel": "TOKOPEDIA", "orders": 36}, {"channel": "Tokopedia ", "orders": 34}, {"channel": "Tokopdia", "orders": 34}, {"channel": "Shopee ", "orders": 34}, {"channel": "Tiktok Shop", "orders": 33}, {"channel": "TikTok shop", "orders": 33}, {"channel": "webstore", "orders": 32}, {"channel": "tiktok shop", "orders": 32}, {"channel": "shopee", "orders": 28}, {"channel": "SHOPEE", "orders": 27}, {"channel": " Tokopedia", "orders": 27}], "description_en": "Returns the correct 23 row(s) with the right values", "description_id": "Mengembalikan 23 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["channel", "orders"], "description_en": "Returns the required columns: channel, orders", "description_id": "Mengembalikan kolom yang diminta: channel, orders", "points": 30}]'::jsonb,
    hints_en = '["WHERE filters rows before grouping", "COUNT(*) counts rows in each group"]'::jsonb,
    hints_id = '["WHERE memfilter baris sebelum pengelompokan", "COUNT(*) menghitung baris di tiap grup"]'::jsonb,
    difficulty = 'easy',
    dataset_name = 'seduh'
FROM public.sessions s
WHERE e.session_id = s.id AND s.session_number = 'X04' AND e.order_num = 2;

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Which Channels Does Seduh Sell On?', 'Seduh Berjualan di Channel Apa Saja?', 'Count the **completed** orders per sales channel. Remember: only `order_status = ''Completed''` counts. Return exactly: `channel`, `orders`, busiest first. The data is raw, so you will get far more than four channels — that mess is the finding.', 'Hitung jumlah order **Completed** per channel penjualan. Ingat: hanya `order_status = ''Completed''` yang dihitung. Kembalikan tepat: `channel`, `orders`, terbanyak dulu. Datanya mentah, jadi channel-nya akan jauh lebih dari empat — keberantakan itulah temuannya.',
  '-- Completed orders per channel
-- Return: channel, orders
', 'SELECT channel, COUNT(*) AS orders FROM orders WHERE order_status = ''Completed'' GROUP BY channel ORDER BY orders DESC;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"channel": "Tokopedia", "orders": 6857}, {"channel": "Shopee", "orders": 6520}, {"channel": "Webstore", "orders": 5073}, {"channel": "TikTok Shop", "orders": 4838}, {"channel": "Webstore ", "orders": 52}, {"channel": "tokopedia", "orders": 50}, {"channel": " Webstore", "orders": 50}, {"channel": "WEBSTORE", "orders": 45}, {"channel": "Shoppee", "orders": 44}, {"channel": " Shopee", "orders": 44}, {"channel": "Tiktok shop ", "orders": 39}, {"channel": "TIKTOK SHOP", "orders": 37}, {"channel": "TOKOPEDIA", "orders": 36}, {"channel": "Tokopedia ", "orders": 34}, {"channel": "Tokopdia", "orders": 34}, {"channel": "Shopee ", "orders": 34}, {"channel": "Tiktok Shop", "orders": 33}, {"channel": "TikTok shop", "orders": 33}, {"channel": "webstore", "orders": 32}, {"channel": "tiktok shop", "orders": 32}, {"channel": "shopee", "orders": 28}, {"channel": "SHOPEE", "orders": 27}, {"channel": " Tokopedia", "orders": 27}], "description_en": "Returns the correct 23 row(s) with the right values", "description_id": "Mengembalikan 23 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["channel", "orders"], "description_en": "Returns the required columns: channel, orders", "description_id": "Mengembalikan kolom yang diminta: channel, orders", "points": 30}]'::jsonb,
  '["WHERE filters rows before grouping", "COUNT(*) counts rows in each group"]'::jsonb,
  '["WHERE memfilter baris sebelum pengelompokan", "COUNT(*) menghitung baris di tiap grup"]'::jsonb,
  'easy', 'seduh', 2
FROM public.sessions s
WHERE s.session_number = 'X04'
  AND NOT EXISTS (
    SELECT 1 FROM public.exercises x
    WHERE x.session_id = s.id AND x.order_num = 2);

-- #3 — Q2 — Which Channel Is Most Valuable After Discount?
UPDATE public.exercises e
SET type = 'sql',
    title_en = 'Q2 — Which Channel Is Most Valuable After Discount?',
    title_id = 'Q2 — Channel Mana yang Paling Bernilai Setelah Diskon?',
    description_en = 'Gross revenue flatters a discount-heavy channel. Compute revenue **after** discount: `quantity * unit_price * (1 - discount_pct)`, completed orders only. Return exactly: `channel`, `revenue` (rounded, no decimals), highest first. Raw channel spellings split one channel across several rows; say so in your answer.',
    description_id = 'Revenue kotor membuat channel yang banyak diskon terlihat bagus. Hitung revenue **setelah** diskon: `quantity * unit_price * (1 - discount_pct)`, hanya order Completed. Kembalikan tepat: `channel`, `revenue` (dibulatkan, tanpa desimal), tertinggi dulu. Penulisan channel yang mentah memecah satu channel jadi beberapa baris; sebutkan itu di jawabanmu.',
    starter_code = '-- Q2: revenue after discount, per channel
-- Return: channel, revenue
',
    solution_code = 'SELECT channel, ROUND(SUM(quantity * unit_price * (1 - discount_pct))) AS revenue FROM orders WHERE order_status = ''Completed'' GROUP BY channel ORDER BY revenue DESC;',
    test_cases = '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"channel": "Tokopedia", "revenue": 1927430950.0}, {"channel": "Shopee", "revenue": 1844757800.0}, {"channel": "Webstore", "revenue": 1429215550.0}, {"channel": "TikTok Shop", "revenue": 1378095650.0}, {"channel": "Webstore ", "revenue": 14944100.0}, {"channel": " Webstore", "revenue": 14804050.0}, {"channel": "Shoppee", "revenue": 14233650.0}, {"channel": " Shopee", "revenue": 13199750.0}, {"channel": "tokopedia", "revenue": 12777950.0}, {"channel": "TikTok shop", "revenue": 12774900.0}, {"channel": "TOKOPEDIA", "revenue": 11485450.0}, {"channel": "Tiktok shop ", "revenue": 11083500.0}, {"channel": "WEBSTORE", "revenue": 10929850.0}, {"channel": "TIKTOK SHOP", "revenue": 10331050.0}, {"channel": "Tiktok Shop", "revenue": 9359900.0}, {"channel": "Shopee ", "revenue": 9201100.0}, {"channel": "Tokopedia ", "revenue": 9141850.0}, {"channel": "shopee", "revenue": 9041100.0}, {"channel": "Tokopdia", "revenue": 8471350.0}, {"channel": "tiktok shop", "revenue": 8157250.0}, {"channel": "SHOPEE", "revenue": 8074950.0}, {"channel": "webstore", "revenue": 7834750.0}, {"channel": " Tokopedia", "revenue": 6844200.0}], "description_en": "Returns the correct 23 row(s) with the right values", "description_id": "Mengembalikan 23 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["channel", "revenue"], "description_en": "Returns the required columns: channel, revenue", "description_id": "Mengembalikan kolom yang diminta: channel, revenue", "points": 30}]'::jsonb,
    hints_en = '["Discount is a fraction — multiply by (1 - discount_pct)", "Wrap the SUM in ROUND() so the result has no decimals"]'::jsonb,
    hints_id = '["Diskon berupa pecahan — kalikan dengan (1 - discount_pct)", "Bungkus SUM dengan ROUND() agar hasilnya tanpa desimal"]'::jsonb,
    difficulty = 'medium',
    dataset_name = 'seduh'
FROM public.sessions s
WHERE e.session_id = s.id AND s.session_number = 'X04' AND e.order_num = 3;

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Q2 — Which Channel Is Most Valuable After Discount?', 'Q2 — Channel Mana yang Paling Bernilai Setelah Diskon?', 'Gross revenue flatters a discount-heavy channel. Compute revenue **after** discount: `quantity * unit_price * (1 - discount_pct)`, completed orders only. Return exactly: `channel`, `revenue` (rounded, no decimals), highest first. Raw channel spellings split one channel across several rows; say so in your answer.', 'Revenue kotor membuat channel yang banyak diskon terlihat bagus. Hitung revenue **setelah** diskon: `quantity * unit_price * (1 - discount_pct)`, hanya order Completed. Kembalikan tepat: `channel`, `revenue` (dibulatkan, tanpa desimal), tertinggi dulu. Penulisan channel yang mentah memecah satu channel jadi beberapa baris; sebutkan itu di jawabanmu.',
  '-- Q2: revenue after discount, per channel
-- Return: channel, revenue
', 'SELECT channel, ROUND(SUM(quantity * unit_price * (1 - discount_pct))) AS revenue FROM orders WHERE order_status = ''Completed'' GROUP BY channel ORDER BY revenue DESC;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"channel": "Tokopedia", "revenue": 1927430950.0}, {"channel": "Shopee", "revenue": 1844757800.0}, {"channel": "Webstore", "revenue": 1429215550.0}, {"channel": "TikTok Shop", "revenue": 1378095650.0}, {"channel": "Webstore ", "revenue": 14944100.0}, {"channel": " Webstore", "revenue": 14804050.0}, {"channel": "Shoppee", "revenue": 14233650.0}, {"channel": " Shopee", "revenue": 13199750.0}, {"channel": "tokopedia", "revenue": 12777950.0}, {"channel": "TikTok shop", "revenue": 12774900.0}, {"channel": "TOKOPEDIA", "revenue": 11485450.0}, {"channel": "Tiktok shop ", "revenue": 11083500.0}, {"channel": "WEBSTORE", "revenue": 10929850.0}, {"channel": "TIKTOK SHOP", "revenue": 10331050.0}, {"channel": "Tiktok Shop", "revenue": 9359900.0}, {"channel": "Shopee ", "revenue": 9201100.0}, {"channel": "Tokopedia ", "revenue": 9141850.0}, {"channel": "shopee", "revenue": 9041100.0}, {"channel": "Tokopdia", "revenue": 8471350.0}, {"channel": "tiktok shop", "revenue": 8157250.0}, {"channel": "SHOPEE", "revenue": 8074950.0}, {"channel": "webstore", "revenue": 7834750.0}, {"channel": " Tokopedia", "revenue": 6844200.0}], "description_en": "Returns the correct 23 row(s) with the right values", "description_id": "Mengembalikan 23 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["channel", "revenue"], "description_en": "Returns the required columns: channel, revenue", "description_id": "Mengembalikan kolom yang diminta: channel, revenue", "points": 30}]'::jsonb,
  '["Discount is a fraction — multiply by (1 - discount_pct)", "Wrap the SUM in ROUND() so the result has no decimals"]'::jsonb,
  '["Diskon berupa pecahan — kalikan dengan (1 - discount_pct)", "Bungkus SUM dengan ROUND() agar hasilnya tanpa desimal"]'::jsonb,
  'medium', 'seduh', 3
FROM public.sessions s
WHERE s.session_number = 'X04'
  AND NOT EXISTS (
    SELECT 1 FROM public.exercises x
    WHERE x.session_id = s.id AND x.order_num = 3);

-- #4 — Q1 — Profit by Category, Not Revenue
UPDATE public.exercises e
SET type = 'sql',
    title_en = 'Q1 — Profit by Category, Not Revenue',
    title_id = 'Q1 — Profit per Kategori, Bukan Revenue',
    description_en = 'The category that sells most is not always the one that earns most. `unit_cost` lives in `products`, so you need a JOIN. Profit per line is `quantity * (unit_price * (1 - discount_pct) - unit_cost)`, completed orders only. Return exactly: `category`, `profit` (rounded), highest first. Inconsistent category names split two of the six categories in two — that is what Session 2 will fix.',
    description_id = 'Kategori yang paling laku belum tentu yang paling untung. `unit_cost` ada di `products`, jadi kamu butuh JOIN. Profit per baris = `quantity * (unit_price * (1 - discount_pct) - unit_cost)`, hanya order Completed. Kembalikan tepat: `category`, `profit` (dibulatkan), tertinggi dulu. Penamaan kategori yang tidak konsisten memecah dua dari enam kategori — itulah yang akan diperbaiki di Sesi 2.',
    starter_code = '-- Q1: profit per category (needs products.unit_cost)
-- Return: category, profit
',
    solution_code = 'SELECT p.category, ROUND(SUM(o.quantity * (o.unit_price * (1 - o.discount_pct) - p.unit_cost))) AS profit FROM orders o JOIN products p ON p.product_id = o.product_id WHERE o.order_status = ''Completed'' GROUP BY p.category ORDER BY profit DESC;',
    test_cases = '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"category": "Roasted Beans", "profit": 1700364150.0}, {"category": "Accessories", "profit": 317251600.0}, {"category": "Brewing Equipment", "profit": 243978650.0}, {"category": "Subscription", "profit": 231213900.0}, {"category": "Gift Set", "profit": 219041700.0}, {"category": "Ready to Drink", "profit": 207704650.0}, {"category": "Ready-to-Drink", "profit": 186977600.0}, {"category": "Roasted Beans ", "profit": 141378900.0}, {"category": "Gift set", "profit": 19233500.0}], "description_en": "Returns the correct 9 row(s) with the right values", "description_id": "Mengembalikan 9 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["category", "profit"], "description_en": "Returns the required columns: category, profit", "description_id": "Mengembalikan kolom yang diminta: category, profit", "points": 30}]'::jsonb,
    hints_en = '["JOIN products ON p.product_id = o.product_id", "Subtract unit_cost per unit, then multiply by quantity"]'::jsonb,
    hints_id = '["JOIN products ON p.product_id = o.product_id", "Kurangi unit_cost per unit, lalu kalikan dengan quantity"]'::jsonb,
    difficulty = 'medium',
    dataset_name = 'seduh'
FROM public.sessions s
WHERE e.session_id = s.id AND s.session_number = 'X04' AND e.order_num = 4;

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Q1 — Profit by Category, Not Revenue', 'Q1 — Profit per Kategori, Bukan Revenue', 'The category that sells most is not always the one that earns most. `unit_cost` lives in `products`, so you need a JOIN. Profit per line is `quantity * (unit_price * (1 - discount_pct) - unit_cost)`, completed orders only. Return exactly: `category`, `profit` (rounded), highest first. Inconsistent category names split two of the six categories in two — that is what Session 2 will fix.', 'Kategori yang paling laku belum tentu yang paling untung. `unit_cost` ada di `products`, jadi kamu butuh JOIN. Profit per baris = `quantity * (unit_price * (1 - discount_pct) - unit_cost)`, hanya order Completed. Kembalikan tepat: `category`, `profit` (dibulatkan), tertinggi dulu. Penamaan kategori yang tidak konsisten memecah dua dari enam kategori — itulah yang akan diperbaiki di Sesi 2.',
  '-- Q1: profit per category (needs products.unit_cost)
-- Return: category, profit
', 'SELECT p.category, ROUND(SUM(o.quantity * (o.unit_price * (1 - o.discount_pct) - p.unit_cost))) AS profit FROM orders o JOIN products p ON p.product_id = o.product_id WHERE o.order_status = ''Completed'' GROUP BY p.category ORDER BY profit DESC;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"category": "Roasted Beans", "profit": 1700364150.0}, {"category": "Accessories", "profit": 317251600.0}, {"category": "Brewing Equipment", "profit": 243978650.0}, {"category": "Subscription", "profit": 231213900.0}, {"category": "Gift Set", "profit": 219041700.0}, {"category": "Ready to Drink", "profit": 207704650.0}, {"category": "Ready-to-Drink", "profit": 186977600.0}, {"category": "Roasted Beans ", "profit": 141378900.0}, {"category": "Gift set", "profit": 19233500.0}], "description_en": "Returns the correct 9 row(s) with the right values", "description_id": "Mengembalikan 9 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["category", "profit"], "description_en": "Returns the required columns: category, profit", "description_id": "Mengembalikan kolom yang diminta: category, profit", "points": 30}]'::jsonb,
  '["JOIN products ON p.product_id = o.product_id", "Subtract unit_cost per unit, then multiply by quantity"]'::jsonb,
  '["JOIN products ON p.product_id = o.product_id", "Kurangi unit_cost per unit, lalu kalikan dengan quantity"]'::jsonb,
  'medium', 'seduh', 4
FROM public.sessions s
WHERE s.session_number = 'X04'
  AND NOT EXISTS (
    SELECT 1 FROM public.exercises x
    WHERE x.session_id = s.id AND x.order_num = 4);

-- #5 — Q3 — Monthly Revenue in 2025
UPDATE public.exercises e
SET type = 'sql',
    title_en = 'Q3 — Monthly Revenue in 2025',
    title_id = 'Q3 — Revenue Bulanan di 2025',
    description_en = 'Build the 2025 trend. `order_date` is text in `YYYY-MM-DD` form, so `substr(order_date, 1, 7)` gives you the month. Completed orders only. Return exactly: `month`, `revenue` (rounded), in date order. A few hundred rows still store the date as `dd/mm/yyyy` text, so this filter quietly skips them — check how many before you trust the trend.',
    description_id = 'Bangun tren 2025. `order_date` berupa teks `YYYY-MM-DD`, jadi `substr(order_date, 1, 7)` memberi bulannya. Hanya order Completed. Kembalikan tepat: `month`, `revenue` (dibulatkan), urut tanggal. Beberapa ratus baris masih menyimpan tanggal sebagai teks `dd/mm/yyyy`, jadi filter ini diam-diam melewatkannya — cek berapa banyak sebelum memercayai trennya.',
    starter_code = '-- Q3: monthly revenue for 2025 only
-- Return: month, revenue
',
    solution_code = 'SELECT substr(order_date, 1, 7) AS month, ROUND(SUM(quantity * unit_price * (1 - discount_pct))) AS revenue FROM orders WHERE order_status = ''Completed'' AND order_date >= ''2025-01-01'' AND order_date < ''2026-01-01'' GROUP BY month ORDER BY month;',
    test_cases = '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"month": "2025-01", "revenue": 248762250.0}, {"month": "2025-02", "revenue": 224568000.0}, {"month": "2025-03", "revenue": 340489700.0}, {"month": "2025-04", "revenue": 295243050.0}, {"month": "2025-05", "revenue": 268817500.0}, {"month": "2025-06", "revenue": 282653750.0}, {"month": "2025-07", "revenue": 289363850.0}, {"month": "2025-08", "revenue": 322461700.0}, {"month": "2025-09", "revenue": 326811900.0}, {"month": "2025-10", "revenue": 337617700.0}, {"month": "2025-11", "revenue": 413881800.0}, {"month": "2025-12", "revenue": 385034300.0}], "description_en": "Returns the correct 12 row(s) with the right values", "description_id": "Mengembalikan 12 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["month", "revenue"], "description_en": "Returns the required columns: month, revenue", "description_id": "Mengembalikan kolom yang diminta: month, revenue", "points": 30}]'::jsonb,
    hints_en = '["substr(order_date, 1, 7) turns 2025-03-14 into 2025-03", "Filter the year in WHERE, then GROUP BY the month expression"]'::jsonb,
    hints_id = '["substr(order_date, 1, 7) mengubah 2025-03-14 menjadi 2025-03", "Filter tahunnya di WHERE, lalu GROUP BY ekspresi bulan tersebut"]'::jsonb,
    difficulty = 'medium',
    dataset_name = 'seduh'
FROM public.sessions s
WHERE e.session_id = s.id AND s.session_number = 'X04' AND e.order_num = 5;

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Q3 — Monthly Revenue in 2025', 'Q3 — Revenue Bulanan di 2025', 'Build the 2025 trend. `order_date` is text in `YYYY-MM-DD` form, so `substr(order_date, 1, 7)` gives you the month. Completed orders only. Return exactly: `month`, `revenue` (rounded), in date order. A few hundred rows still store the date as `dd/mm/yyyy` text, so this filter quietly skips them — check how many before you trust the trend.', 'Bangun tren 2025. `order_date` berupa teks `YYYY-MM-DD`, jadi `substr(order_date, 1, 7)` memberi bulannya. Hanya order Completed. Kembalikan tepat: `month`, `revenue` (dibulatkan), urut tanggal. Beberapa ratus baris masih menyimpan tanggal sebagai teks `dd/mm/yyyy`, jadi filter ini diam-diam melewatkannya — cek berapa banyak sebelum memercayai trennya.',
  '-- Q3: monthly revenue for 2025 only
-- Return: month, revenue
', 'SELECT substr(order_date, 1, 7) AS month, ROUND(SUM(quantity * unit_price * (1 - discount_pct))) AS revenue FROM orders WHERE order_status = ''Completed'' AND order_date >= ''2025-01-01'' AND order_date < ''2026-01-01'' GROUP BY month ORDER BY month;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"month": "2025-01", "revenue": 248762250.0}, {"month": "2025-02", "revenue": 224568000.0}, {"month": "2025-03", "revenue": 340489700.0}, {"month": "2025-04", "revenue": 295243050.0}, {"month": "2025-05", "revenue": 268817500.0}, {"month": "2025-06", "revenue": 282653750.0}, {"month": "2025-07", "revenue": 289363850.0}, {"month": "2025-08", "revenue": 322461700.0}, {"month": "2025-09", "revenue": 326811900.0}, {"month": "2025-10", "revenue": 337617700.0}, {"month": "2025-11", "revenue": 413881800.0}, {"month": "2025-12", "revenue": 385034300.0}], "description_en": "Returns the correct 12 row(s) with the right values", "description_id": "Mengembalikan 12 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["month", "revenue"], "description_en": "Returns the required columns: month, revenue", "description_id": "Mengembalikan kolom yang diminta: month, revenue", "points": 30}]'::jsonb,
  '["substr(order_date, 1, 7) turns 2025-03-14 into 2025-03", "Filter the year in WHERE, then GROUP BY the month expression"]'::jsonb,
  '["substr(order_date, 1, 7) mengubah 2025-03-14 menjadi 2025-03", "Filter tahunnya di WHERE, lalu GROUP BY ekspresi bulan tersebut"]'::jsonb,
  'medium', 'seduh', 5
FROM public.sessions s
WHERE s.session_number = 'X04'
  AND NOT EXISTS (
    SELECT 1 FROM public.exercises x
    WHERE x.session_id = s.id AND x.order_num = 5);

-- #6 — Cities Worth Their Own Campaign
UPDATE public.exercises e
SET type = 'sql',
    title_en = 'Cities Worth Their Own Campaign',
    title_id = 'Kota yang Layak Dapat Kampanye Sendiri',
    description_en = 'Marketing wants to launch city-level campaigns, but only where the volume justifies it — cities with more than 900 completed orders. Which cities clear that bar? Return exactly: `city`, `orders`, busiest first.',
    description_id = 'Tim marketing ingin meluncurkan kampanye di level kota, tapi hanya di kota dengan volume yang cukup besar — lebih dari 900 order Completed. Kota mana saja yang lolos? Kembalikan tepat: `city`, `orders`, terbanyak dulu.',
    starter_code = '-- Cities with more than 900 completed orders
-- Return: city, orders
',
    solution_code = 'SELECT city, COUNT(*) AS orders FROM orders WHERE order_status = ''Completed'' GROUP BY city HAVING COUNT(*) > 900 ORDER BY orders DESC;',
    test_cases = '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"city": "Balikpapan", "orders": 4403}, {"city": "Bandung", "orders": 2589}, {"city": "Surabaya", "orders": 2261}, {"city": "Semarang", "orders": 1413}, {"city": "Bekasi", "orders": 1396}, {"city": "Medan", "orders": 1202}, {"city": "Tangerang", "orders": 1170}, {"city": "Depok", "orders": 1113}, {"city": "Malang", "orders": 1105}, {"city": "Yogyakarta", "orders": 936}, {"city": "Bogor", "orders": 914}], "description_en": "Returns the correct 11 row(s) with the right values", "description_id": "Mengembalikan 11 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["city", "orders"], "description_en": "Returns the required columns: city, orders", "description_id": "Mengembalikan kolom yang diminta: city, orders", "points": 30}]'::jsonb,
    hints_en = '["WHERE runs before grouping, HAVING runs after", "You still need the completed-orders filter in WHERE"]'::jsonb,
    hints_id = '["WHERE berjalan sebelum pengelompokan, HAVING sesudahnya", "Filter order Completed tetap diperlukan di WHERE"]'::jsonb,
    difficulty = 'hard',
    dataset_name = 'seduh'
FROM public.sessions s
WHERE e.session_id = s.id AND s.session_number = 'X04' AND e.order_num = 6;

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Cities Worth Their Own Campaign', 'Kota yang Layak Dapat Kampanye Sendiri', 'Marketing wants to launch city-level campaigns, but only where the volume justifies it — cities with more than 900 completed orders. Which cities clear that bar? Return exactly: `city`, `orders`, busiest first.', 'Tim marketing ingin meluncurkan kampanye di level kota, tapi hanya di kota dengan volume yang cukup besar — lebih dari 900 order Completed. Kota mana saja yang lolos? Kembalikan tepat: `city`, `orders`, terbanyak dulu.',
  '-- Cities with more than 900 completed orders
-- Return: city, orders
', 'SELECT city, COUNT(*) AS orders FROM orders WHERE order_status = ''Completed'' GROUP BY city HAVING COUNT(*) > 900 ORDER BY orders DESC;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"city": "Balikpapan", "orders": 4403}, {"city": "Bandung", "orders": 2589}, {"city": "Surabaya", "orders": 2261}, {"city": "Semarang", "orders": 1413}, {"city": "Bekasi", "orders": 1396}, {"city": "Medan", "orders": 1202}, {"city": "Tangerang", "orders": 1170}, {"city": "Depok", "orders": 1113}, {"city": "Malang", "orders": 1105}, {"city": "Yogyakarta", "orders": 936}, {"city": "Bogor", "orders": 914}], "description_en": "Returns the correct 11 row(s) with the right values", "description_id": "Mengembalikan 11 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["city", "orders"], "description_en": "Returns the required columns: city, orders", "description_id": "Mengembalikan kolom yang diminta: city, orders", "points": 30}]'::jsonb,
  '["WHERE runs before grouping, HAVING runs after", "You still need the completed-orders filter in WHERE"]'::jsonb,
  '["WHERE berjalan sebelum pengelompokan, HAVING sesudahnya", "Filter order Completed tetap diperlukan di WHERE"]'::jsonb,
  'hard', 'seduh', 6
FROM public.sessions s
WHERE s.session_number = 'X04'
  AND NOT EXISTS (
    SELECT 1 FROM public.exercises x
    WHERE x.session_id = s.id AND x.order_num = 6);

-- #7 — Q6 — Which Acquisition Channel Brings the Best Customers?
UPDATE public.exercises e
SET type = 'sql',
    title_en = 'Q6 — Which Acquisition Channel Brings the Best Customers?',
    title_id = 'Q6 — Channel Akuisisi Mana yang Membawa Customer Terbaik?',
    description_en = 'Marketing spends across six acquisition channels, but which ones actually bring customers who buy, not just click? For each channel, compare how many distinct customers converted and how much revenue they generated (completed orders only). Return exactly: `acquisition_channel`, `customers` (distinct buyers), `revenue` (rounded), highest revenue first.',
    description_id = 'Tim marketing beriklan lewat enam acquisition channel, tapi channel mana yang benar-benar mendatangkan pembeli, bukan sekadar klik? Untuk tiap channel, bandingkan berapa banyak pelanggan unik yang benar-benar membeli dan berapa revenue yang mereka hasilkan (hanya order Completed). Kembalikan tepat: `acquisition_channel`, `customers` (pembeli unik), `revenue` (dibulatkan), revenue tertinggi dulu.',
    starter_code = '-- Q6: value of each acquisition channel
-- Return: acquisition_channel, customers, revenue
',
    solution_code = 'SELECT c.acquisition_channel, COUNT(DISTINCT o.customer_id) AS customers, ROUND(SUM(o.quantity * o.unit_price * (1 - o.discount_pct))) AS revenue FROM orders o JOIN customers c ON c.customer_id = o.customer_id WHERE o.order_status = ''Completed'' GROUP BY c.acquisition_channel ORDER BY revenue DESC;',
    test_cases = '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"acquisition_channel": "Instagram Ads", "customers": 3271, "revenue": 1517831600.0}, {"acquisition_channel": "Google Search", "customers": 2220, "revenue": 1379529900.0}, {"acquisition_channel": "Referral", "customers": 1854, "revenue": 1341542300.0}, {"acquisition_channel": "Organic Social", "customers": 2395, "revenue": 1310689900.0}, {"acquisition_channel": "TikTok Ads", "customers": 1987, "revenue": 650212300.0}, {"acquisition_channel": "Marketplace", "customers": 1653, "revenue": 582384650.0}], "description_en": "Returns the correct 6 row(s) with the right values", "description_id": "Mengembalikan 6 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["acquisition_channel", "customers", "revenue"], "description_en": "Returns the required columns: acquisition_channel, customers, revenue", "description_id": "Mengembalikan kolom yang diminta: acquisition_channel, customers, revenue", "points": 30}]'::jsonb,
    hints_en = '["COUNT(DISTINCT ...) so a repeat buyer is not counted twice", "Spend lives in marketing_spend, but its channel names differ — that is the next step"]'::jsonb,
    hints_id = '["COUNT(DISTINCT ...) agar repeat buyer tidak terhitung dua kali", "Spend ada di marketing_spend, tapi nama channel-nya berbeda — itu langkah berikutnya"]'::jsonb,
    difficulty = 'hard',
    dataset_name = 'seduh'
FROM public.sessions s
WHERE e.session_id = s.id AND s.session_number = 'X04' AND e.order_num = 7;

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Q6 — Which Acquisition Channel Brings the Best Customers?', 'Q6 — Channel Akuisisi Mana yang Membawa Customer Terbaik?', 'Marketing spends across six acquisition channels, but which ones actually bring customers who buy, not just click? For each channel, compare how many distinct customers converted and how much revenue they generated (completed orders only). Return exactly: `acquisition_channel`, `customers` (distinct buyers), `revenue` (rounded), highest revenue first.', 'Tim marketing beriklan lewat enam acquisition channel, tapi channel mana yang benar-benar mendatangkan pembeli, bukan sekadar klik? Untuk tiap channel, bandingkan berapa banyak pelanggan unik yang benar-benar membeli dan berapa revenue yang mereka hasilkan (hanya order Completed). Kembalikan tepat: `acquisition_channel`, `customers` (pembeli unik), `revenue` (dibulatkan), revenue tertinggi dulu.',
  '-- Q6: value of each acquisition channel
-- Return: acquisition_channel, customers, revenue
', 'SELECT c.acquisition_channel, COUNT(DISTINCT o.customer_id) AS customers, ROUND(SUM(o.quantity * o.unit_price * (1 - o.discount_pct))) AS revenue FROM orders o JOIN customers c ON c.customer_id = o.customer_id WHERE o.order_status = ''Completed'' GROUP BY c.acquisition_channel ORDER BY revenue DESC;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"acquisition_channel": "Instagram Ads", "customers": 3271, "revenue": 1517831600.0}, {"acquisition_channel": "Google Search", "customers": 2220, "revenue": 1379529900.0}, {"acquisition_channel": "Referral", "customers": 1854, "revenue": 1341542300.0}, {"acquisition_channel": "Organic Social", "customers": 2395, "revenue": 1310689900.0}, {"acquisition_channel": "TikTok Ads", "customers": 1987, "revenue": 650212300.0}, {"acquisition_channel": "Marketplace", "customers": 1653, "revenue": 582384650.0}], "description_en": "Returns the correct 6 row(s) with the right values", "description_id": "Mengembalikan 6 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["acquisition_channel", "customers", "revenue"], "description_en": "Returns the required columns: acquisition_channel, customers, revenue", "description_id": "Mengembalikan kolom yang diminta: acquisition_channel, customers, revenue", "points": 30}]'::jsonb,
  '["COUNT(DISTINCT ...) so a repeat buyer is not counted twice", "Spend lives in marketing_spend, but its channel names differ — that is the next step"]'::jsonb,
  '["COUNT(DISTINCT ...) agar repeat buyer tidak terhitung dua kali", "Spend ada di marketing_spend, tapi nama channel-nya berbeda — itu langkah berikutnya"]'::jsonb,
  'hard', 'seduh', 7
FROM public.sessions s
WHERE s.session_number = 'X04'
  AND NOT EXISTS (
    SELECT 1 FROM public.exercises x
    WHERE x.session_id = s.id AND x.order_num = 7);

-- #8 — Q7 — Does Discounting Actually Pay?
UPDATE public.exercises e
SET type = 'sql',
    title_en = 'Q7 — Does Discounting Actually Pay?',
    title_id = 'Q7 — Apakah Diskon Benar-benar Menguntungkan?',
    description_en = 'Sales keeps pushing deeper discounts to move volume, but does it actually pay off? For each discount tier, compare average order quantity against margin (`profit / revenue * 100`) on completed orders. Return exactly: `discount_pct`, `avg_quantity` (rounded to 2 decimals), `margin_pct` (rounded to 1 decimal), by discount ascending. Read the answer off your own result.',
    description_id = 'Tim sales terus mendorong diskon yang lebih dalam demi mengejar volume, tapi apakah itu benar-benar menguntungkan? Untuk tiap tingkat diskon, bandingkan rata-rata quantity per order dengan margin (`profit / revenue * 100`) pada order Completed. Kembalikan tepat: `discount_pct`, `avg_quantity` (2 desimal), `margin_pct` (1 desimal), urut diskon menaik. Baca jawabannya dari hasilmu sendiri.',
    starter_code = '-- Q7: discount depth vs volume vs margin
-- Return: discount_pct, avg_quantity, margin_pct
',
    solution_code = 'SELECT o.discount_pct, ROUND(AVG(o.quantity), 2) AS avg_quantity, ROUND(SUM(o.quantity * (o.unit_price * (1 - o.discount_pct) - p.unit_cost)) * 100.0 / SUM(o.quantity * o.unit_price * (1 - o.discount_pct)), 1) AS margin_pct FROM orders o JOIN products p ON p.product_id = o.product_id WHERE o.order_status = ''Completed'' GROUP BY o.discount_pct ORDER BY o.discount_pct;',
    test_cases = '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"discount_pct": 0.0, "avg_quantity": 2.17, "margin_pct": 51.3}, {"discount_pct": 0.05, "avg_quantity": 2.52, "margin_pct": 49.0}, {"discount_pct": 0.1, "avg_quantity": 2.82, "margin_pct": 46.3}, {"discount_pct": 0.15, "avg_quantity": 3.03, "margin_pct": 43.4}, {"discount_pct": 0.2, "avg_quantity": 3.28, "margin_pct": 39.4}, {"discount_pct": 0.25, "avg_quantity": 3.55, "margin_pct": 35.4}], "description_en": "Returns the correct 6 row(s) with the right values", "description_id": "Mengembalikan 6 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["discount_pct", "avg_quantity", "margin_pct"], "description_en": "Returns the required columns: discount_pct, avg_quantity, margin_pct", "description_id": "Mengembalikan kolom yang diminta: discount_pct, avg_quantity, margin_pct", "points": 30}]'::jsonb,
    hints_en = '["Compute profit and revenue in the same query, then divide", "Multiply by 100.0 — integer division would flatten the result to 0"]'::jsonb,
    hints_id = '["Hitung profit dan revenue dalam satu query, lalu bagi", "Kalikan dengan 100.0 — pembagian integer akan membuat hasilnya 0"]'::jsonb,
    difficulty = 'hard',
    dataset_name = 'seduh'
FROM public.sessions s
WHERE e.session_id = s.id AND s.session_number = 'X04' AND e.order_num = 8;

INSERT INTO public.exercises (session_id, type, title_en, title_id, description_en, description_id,
  starter_code, solution_code, test_cases, hints_en, hints_id, difficulty, dataset_name, order_num)
SELECT s.id, 'sql', 'Q7 — Does Discounting Actually Pay?', 'Q7 — Apakah Diskon Benar-benar Menguntungkan?', 'Sales keeps pushing deeper discounts to move volume, but does it actually pay off? For each discount tier, compare average order quantity against margin (`profit / revenue * 100`) on completed orders. Return exactly: `discount_pct`, `avg_quantity` (rounded to 2 decimals), `margin_pct` (rounded to 1 decimal), by discount ascending. Read the answer off your own result.', 'Tim sales terus mendorong diskon yang lebih dalam demi mengejar volume, tapi apakah itu benar-benar menguntungkan? Untuk tiap tingkat diskon, bandingkan rata-rata quantity per order dengan margin (`profit / revenue * 100`) pada order Completed. Kembalikan tepat: `discount_pct`, `avg_quantity` (2 desimal), `margin_pct` (1 desimal), urut diskon menaik. Baca jawabannya dari hasilmu sendiri.',
  '-- Q7: discount depth vs volume vs margin
-- Return: discount_pct, avg_quantity, margin_pct
', 'SELECT o.discount_pct, ROUND(AVG(o.quantity), 2) AS avg_quantity, ROUND(SUM(o.quantity * (o.unit_price * (1 - o.discount_pct) - p.unit_cost)) * 100.0 / SUM(o.quantity * o.unit_price * (1 - o.discount_pct)), 1) AS margin_pct FROM orders o JOIN products p ON p.product_id = o.product_id WHERE o.order_status = ''Completed'' GROUP BY o.discount_pct ORDER BY o.discount_pct;',
  '[{"id": "tc1", "validation_type": "exact_match", "expected_rows": [{"discount_pct": 0.0, "avg_quantity": 2.17, "margin_pct": 51.3}, {"discount_pct": 0.05, "avg_quantity": 2.52, "margin_pct": 49.0}, {"discount_pct": 0.1, "avg_quantity": 2.82, "margin_pct": 46.3}, {"discount_pct": 0.15, "avg_quantity": 3.03, "margin_pct": 43.4}, {"discount_pct": 0.2, "avg_quantity": 3.28, "margin_pct": 39.4}, {"discount_pct": 0.25, "avg_quantity": 3.55, "margin_pct": 35.4}], "description_en": "Returns the correct 6 row(s) with the right values", "description_id": "Mengembalikan 6 baris yang benar dengan nilai yang tepat", "points": 70}, {"id": "tc2", "validation_type": "contains_columns", "expected_columns": ["discount_pct", "avg_quantity", "margin_pct"], "description_en": "Returns the required columns: discount_pct, avg_quantity, margin_pct", "description_id": "Mengembalikan kolom yang diminta: discount_pct, avg_quantity, margin_pct", "points": 30}]'::jsonb,
  '["Compute profit and revenue in the same query, then divide", "Multiply by 100.0 — integer division would flatten the result to 0"]'::jsonb,
  '["Hitung profit dan revenue dalam satu query, lalu bagi", "Kalikan dengan 100.0 — pembagian integer akan membuat hasilnya 0"]'::jsonb,
  'hard', 'seduh', 8
FROM public.sessions s
WHERE s.session_number = 'X04'
  AND NOT EXISTS (
    SELECT 1 FROM public.exercises x
    WHERE x.session_id = s.id AND x.order_num = 8);
